### ISSUE TITLE
Data retrival problem (Sqlmap) 

### ISSUE THREAD

**Issue by Pen-10** [sqlmapproject/sqlmap#1145]
Hi guys ..

while am extracting password column "varchar(255)" Data received come like this : 
\\?81\\?94\\?90d\\?9d\\?97\\?9c\\?98\
it's not a hash that's for sure , what's the problem !!

dbms:mysql
version : 5.0
technique: error based sql injection

and is there are a way to DISABLE the " heuristically checking if the target is protected by some kind of WAF/IPS/IDS " ??

**Comment by stamparm** [comment]
What's the name of the column? Returned data is clearly in either binary form or it contains international letters which were not properly decoded (e.g. because the used collation in database is different than used character set on the web page). What do you get for `--parse-errors` when retrieving that data? Have you peeked into the web server responses?

Currently there is no way to disable that heuristic check. It's only a single SQLi query, while you potentially run tens of thousands queries afterwards. Give me one reason to disable it (by default) and I'll do it.

**Comment by Pen-10** [comment]
actually there is no errors ( --parse-errors ) gives me nothing at all 
the name of the column is password .

and about the first question ..

there is some websites got a firewall that blocks your ip address after 3 403 or 406 errors for example, and the request of that check is not encrypted by the tempering scripts of course.

so I use a different proxy every Time. It will be great if it's optional :+1:

**Comment by stamparm** [comment]
With the latest commit heuristic check is also affected by used tamper scripts. After this commit you won't be able to find one good reason why this ONE request would be more problematic than potentially tens of thousands of other SQLi requests.

**Comment by stamparm** [comment]
With your column named "password" I can only conclude that the password is stored in binary format of the hash itself. This is not uncommon.

**Comment by stamparm** [comment]
"it's not a hash that's for sure" <- for sure it is. Been there, done that. Also, you have an error-based SQLi, which means that retrieved data is pretty much safe from "random" errors.

p.s. you can try to re-retrieve that table with usage of: "--fresh-queries --binary-fields password". That way you'll force the retrieval of data in HEX format. Afterwards you can manually decode it and try to break it with a tool of choice (e.g. hashcat). Please don't ask for details. Google for it.

**Comment by Pen-10** [comment]
OK thanks man :+1:  , That helped allot
