### ISSUE TITLE
Some time the tamper greatest.py will went wrong

### ISSUE THREAD

**Issue by yichinzhu** [sqlmapproject/sqlmap#1252]
When I use --technique T and --tamper "greatest.py" at the same time, the payload whil turn to a mess.

eg.

C:\Users\yichin\Software\sqlmap>sqlmap.py -r"c:\Users\yichin\Desktop\pig.txt" -p
 "username[0]" --dbms=mysql --prefix "='233' and 1=1 " --suffix "))#BETWEEN" --t
echnique "T" --tamper "greatest.py" --users -v 3

[12:58:02] [PAYLOAD] ='233' and 1=1  AND GREATEST((SELECT * FROM (SELECT(SLEEP(5
-(IF(ORD(MID((SELECT IFNULL(CAST(COUNT(DISTINCT(user)) AS CHAR),0x20) FROM mysql
.user),1,1)),51,0,5)))))LaBX)))#BETWEEN+1)=(SELECT * FROM (SELECT(SLEEP(5-(IF(OR
D(MID((SELECT IFNULL(CAST(COUNT(DISTINCT(user)) AS CHAR),0x20) FROM mysql.user),
1,1))

the suffix(#BETWEEN) turn out in the middle of the payload.

So I writ a script to test the regex written in greatest.py, here is the result:

input: 1 and (a > b)
output: 1 and GREATEST((a,b)+1)=(a

input:1 and a > b
output: 1 and GREATEST(a,b+1)=a

input: 1 and (a > b)
output 1 and GREATEST((a,b)+1)=(a

input: 1 and 233 = if(a > b, a, 233)
output: 1 and GREATEST(233 = if(a,b, a, 233)+1)=233 = if(a

p.s the version of sqlmap i use is 1.0-dev-nongit-20150528

**Comment by stamparm** [comment]
I've made a little patch to the tamper script, but it still won't work in your case. We won't do any more work here because of one simple reason. Your payload is too complicated to be handled by that simpleton script. For example, something like the following:

`1 AND (SELECT * FROM (SELECT(SLEEP(1-(IF(ORD(MID((IFNULL(CAST(VERSION() AS CHAR),0x20)),1,1))>54,0,1)))))CXVP)#`

is simply too complicated to be handled by the tamper script. I would suggest you to use custom script (i.e. your own non-sqlmap program) in cases like yours.
