### ISSUE TITLE
error connect to tor

### ISSUE THREAD

**Issue by DeadNumbers** [sqlmapproject/sqlmap#1574]
sqlmap --tor --tor-type=socks5 --tor-port=9050 --check-tor -u "http://***********************"
         _
 ___ ___| |_____ ___ ___  {1.0-dev-nongit-201511280897}
|_ -| . | |     | .'| . |
|___|_  |_|_|_|_|__,|  _|
      |_|           |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting at 21:02:23

[21:02:23] [WARNING] increasing default value for option '--time-sec' to 10 because switch '--tor' was provided
[21:02:23] [INFO] setting Tor SOCKS proxy settings
[21:02:23] [INFO] checking Tor connection
[21:02:26] [CRITICAL] unable to connect to the target URL or proxy. sqlmap is going to retry the request(s)
[21:02:26] [WARNING] please make sure that you have Tor installed and running so you could successfully use switch '--tor' (e.g. 'https://help.ubuntu.com/community/Tor')
[21:02:28] [CRITICAL] it seems that Tor is not properly set. Please try using options '--tor-type' and/or '--tor-port'

[*] shutting down at 21:02:28

**Comment by stamparm** [comment]
And what is your Tor socks port? Which bundle?

You haven't told anything about the issue itself.

**Comment by DeadNumbers** [comment]
port default, 9050. Tor is work fine, i test it in firefox. This error was if i set `--check-tor`, but i do not have to check possibility change my ip or not if remove `--check-tor`.

**Comment by stamparm** [comment]
OS and which Tor bundle (e.g. Vidalia)?

**Comment by DeadNumbers** [comment]
OS Archlinux, Tor bundle Tor, not Vidalia.

**Comment by stamparm** [comment]
![Uploading tor.png…]()

**Comment by stamparm** [comment]
@DeadNumbers there was indeed a bug (reproducible on Python >= 2.7.9). Got another error report via user on email.

**Comment by sabeesh03** [comment]
tor.service - Anonymizing overlay network for TCP (multi-instance-master)
     Loaded: loaded (/lib/systemd/system/tor.service; disabled; vendor preset: disabled)
     Active: inactive (dead)
root@bheem:~/sqlmap# sudo apt-get install tor
Reading package lists... Done
Building dependency tree       
Reading state information... Done
tor is already the newest version (0.4.4.5-1).
0 upgraded, 0 newly installed, 0 to remove and 423 not upgraded.
root@bheem:~/sqlmap# sudo add-apt-repository ppa:webupd8team/tor-browser
sudo: add-apt-repository: command not found
root@bheem:~/sqlmap# sudo service tor start
root@bheem:~/sqlmap# service tor status
● tor.service - Anonymizing overlay network for TCP (multi-instance-master)
     Loaded: loaded (/lib/systemd/system/tor.service; disabled; vendor preset: disabled)
     Active: active (exited) since Wed 2020-10-14 14:13:54 UTC; 6s ago
    Process: 1607 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
   Main PID: 1607 (code=exited, status=0/SUCCESS)

Oct 14 14:13:54 bheem systemd[1]: Starting Anonymizing overlay network for TCP (multi-instance-master)...
Oct 14 14:13:54 bheem systemd[1]: Finished Anonymizing overlay network for TCP (multi-instance-master).
root@bheem:~/sqlmap# python sqlmap.py -u https://url%20=1 --identify-waf --tamper="between,randomcase,space2comment" -v 3 --random-agent --dbs --tor  --tor-port=9150 --random-agent --check-tor --time-sec 15 -batch        ___
       __H__
 ___ ___[(]_____ ___ ___  {1.4.10.8#dev}
|_ -| . [.]     | .'| . |
|___|_  ["]_|_|_|__,|  _|
      |_|V...       |_|   http://sqlmap.org

[14:14:16] [WARNING] switch/option '--identify-waf' is deprecated (hint: functionality being done automatically)
[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting @ 14:14:16 /2020-10-14/

[14:14:16] [DEBUG] cleaning up configuration parameters
[14:14:16] [INFO] setting Tor SOCKS proxy settings
[14:14:16] [CRITICAL] can't establish connection with the Tor SOCKS proxy. Please make sure that you have Tor service installed and setup so you could be able to successfully use switch '--tor'

[*] ending @ 14:14:16 /2020-10-14/
request guidance plz

**Comment by sabeesh03** [comment]
my tor is not getting connected while using sqlmap

**Comment by stamparm** [comment]
@sabeesh03 you are forcing usage of `--tor-port=9150` and asking for help, while not explaining why did you force that port in the first place, where default port in modern Linux installations is 9050. Also, I can't comprehend why did you touch `--tor-port` in the first place while sqlmap automatically checks for default ports

**Comment by sabeesh03** [comment]
got it thanks stamparm
