### ISSUE TITLE
Problem with \xa0

### ISSUE THREAD

**Issue by Tardis07** [sqlmapproject/sqlmap#1657]
When I dump a database, I got a strange string as '\xa0'… It must be '&nbsp;' in HTML. So how to decode it automatically?

**Comment by shadowfolder** [comment]
Hi, maybe do you tried wit differet CHARSET and --hex?

**Comment by Tardis07** [comment]
It's not related to CHARSET. I'm going to try --hex

**Comment by Tardis07** [comment]
And --hex doesn't work neither.

**Comment by stamparm** [comment]
@Tardis07 I am not sure why this seems to be a problem to you. String "\xa0" means that there was a bytecode \xa0 at the other side, most probably as a leftover because sqlmap couldn't decode it to unicode. This is normal for raw blob data and international letters stored in not compatible charset as the web page being injectable
