### ISSUE TITLE
Faster Blind/Time-based SQL injection

### ISSUE THREAD

**Issue by SuperThunder2342** [sqlmapproject/sqlmap#1783]
Here are some slides with a more efficient blind/time-based SQLi(4 requests/byte) that is pretty stable and I think can be implemented in sqlmap:
https://drive.google.com/file/d/0B0tBYiOD2uG7MkpxaFRWTkhOTTA/view

So what you think guys?

**Comment by stamparm** [comment]
`pretty stable` ->

In boolean based blind proposed technique(s) require `TRUE`, `FALSE`, `ERROR` and `SLEEP` responses for 4 different states (unpractical, unrealistic (because of requirement for ERROR state) and slow because of SLEEP). In time-based blind paper requires 4 discreet states (SLEEP 1, SLEEP 2, SLEEP 3, SLEEP 4) while in real life you only get SLEEP or NOSLEEP. You can't distinguish discreet SLEEP states because of implicit/inherent network and/or server latency.

**Comment by maxway2021** [comment]
https://ilovepentesting.me/how-to-beat-time-based-sqli-8946484ef8a5
