### ISSUE TITLE
Can we edit manually table or column names ?

### ISSUE THREAD

**Issue by iwantaturboman** [sqlmapproject/sqlmap#1844]
Hi all.
Do you know if it possible to edit a `table` or `column` name by editing a sqlmap output file ?
Example : sqlmap can make errors while retrieving data with Time-based blind.
Table name : `Adminis%ration`
1) Can i edit `session.sqlite` file to replace `Adminis%ration` by `Administration`.
2) Can i use a SQL SHELL with this command line : 
`sqlmap.py -u URL --fresh-queries --sql-shell SELECT table_name FROM information_schema.tables WHERE table_schema=database() and table_name LIKE 'Admin%';`

Regards,

**Comment by stamparm** [comment]
1) I would suggest you to not modify the session.sqlite as you'll only get messed up. Lots of data is base64 pickled, while "id"s are hashed values of internal key representation. If something is messed up in the output I would suggest you to rerun the sqlmap with `--fresh-queries`
2) You meant `--sql-query` instead of `--sql-shell`. You can do that, but have to watch out for proper usage of quotes. Example:

```
python sqlmap.py -u "http://testphp.vulnweb.com/artists.php?artist=1" --sql-query "SELECT table_name FROM information_schema.tables WHERE table_schema=database() and table_name LIKE 'artist%'"
...
[10:20:39] [INFO] fetching SQL SELECT statement query output: 'SELECT table_name FROM information_schema.tables WHERE table_schema=database() and table_name LIKE 'artist%''
[10:20:39] [INFO] the SQL query used returns 1 entries
[10:20:39] [INFO] retrieved: artists
SELECT table_name FROM information_schema.tables WHERE table_schema=database() and table_name LIKE 'artist%' [1]:                                                                                                                           
[*] artists
...
