### ISSUE TITLE
keepalive bug in sqlmap

### ISSUE THREAD

**Issue by hysia** [sqlmapproject/sqlmap#1878]
When use the option `--keep-alive`  ， sqlmap will still send http header  `Connection: close`  you can see with  `-v 4` . BTW,  Can you plz upgrade thirdparty module `keepalive` to the new version?  https://github.com/wikier/keepalive

**Comment by stamparm** [comment]
Actually, `Connection: Keep-alive` is used at the end, while `-v 4` reports wrong value. Will patch.

As of updating the module... It won't be happen because it got terrible "multi-threading" support (at least in original version) and other bugs we fixed in our version, like: support for non-GET/POST methods (e.g. PUT), custom header values, etc.

I'll just take a look if something could be "borrowed" from a newer version

**Comment by stamparm** [comment]
p.s. nevertheless, checking if I could incorporate the new version (with slight modifications)

**Comment by stamparm** [comment]
Done. Both incorporated new version of `keepalive.py` (with slight modifications) and fixed the reported `-v 4` bug.

p.s. I expect some hidden bugs with a new `keepalive.py` version now in the following period :D

**Comment by hysia** [comment]
Actually I have found a bug in new `keepalive.py` already last night，and report an issue  ...
