### ISSUE TITLE
Boolean blind vs Union based

### ISSUE THREAD

**Issue by john-bonachon** [sqlmapproject/sqlmap#1959]
Just a question. I've been trying to learn how techniques work.
Boolean based works by doing boolean questions to DB and comparing the content of a success/fail page. In fact, sqlmap does a great job reducing requests up to 7 max per character by using the bisect algorithm.

However, as far as I know in a union based injection the query rows are replaced by the injected query rows, and those results are only visible on the rendered page.

How sqlmap can retrieve that information? by scraping and comparing the content?

What's faster concerning extraction? boolean based or union based injection?

**Comment by lukapusic** [comment]
Union based is much, much faster, because it allows you to retrieve whole columns or even whole rows in a single request. Compare that to ~7 requests per character. To retrieve the content in a Union-based injection, Sqlmap parses HTML and scrapes the content in a smart way, analysing the webpage beforehand to determine which content to retrieve and which to ignore.

**Comment by john-bonachon** [comment]
Ok, if sqlmap succeds with 3 techniques (say, boolean-based, time-based and union-based). Which one will it choose to build the requests?

When union-based, how can sqlmap distinguish between field values in html response ?!

**Comment by stamparm** [comment]
1) It chooses the fastest (union is fastest, then comes the error-based, then comes the boolean, etc.)
2) It uses concatenation of the result with some random choosen prefix and suffix values (e.g. ABC at start and XYZ at end). Everything between those prefix and suffix values at the resulting page is considered to be a result of UNION query

**Comment by john-bonachon** [comment]
clever!
