### ISSUE TITLE
utf8 data retrival problem

### ISSUE THREAD

**Issue by mpour** [sqlmapproject/sqlmap#2090]
hi,
 I used the switch --charset=utf8 to get table name from mssql  db. 
I  use linux (ubuntu) and --charset=utf8 in a query but I still have problem and get this symbolic ???? data.
what can I do to solve it?

**Comment by stamparm** [comment]
1) First of all, you haven't stated which techniques have been recognized by sqlmap as usable. In some cases there is an inevitable data loss because of charset incompatibility (usually between data storage layer and data connector and/or presentation layer)
2) You can try to force some other technique than the one used (e.g. `--technique=B`)
3) You can try to retrieve data with `--hex` or `--binary-fields`
