### ISSUE TITLE
Injection across multiple parameters

### ISSUE THREAD

**Issue by squarefractal** [sqlmapproject/sqlmap#2100]
I'm trying to bypass a WAF that makes quite a lot of injections through a single parameter impossible by blocking requests that contain the two strings 'select' and 'union' in the same parameter. However, splitting it across two parameters works; I don't see a way to have sqlmap inject it though.

Is there a way I can make sqlmap do injection across multiple params? If not, can this be looked into as an enhancement?

**Comment by stamparm** [comment]
Which platform are you talking about (PHP, ASP,..)? Each platform has its own way of concatenating parameter values and rarely one of them support this kind of attacks. Sqlmap has a --hpp switch which attacks mostly the ASP platform by HTTP parameter pollution.

Also, you haven't stated at least one request that worked on your case. That would prevent a guessing game here.

**Comment by squarefractal** [comment]
Sorry for not being clear, this isn't parameter pollution, but rather parameter fragmentation.

The application has a query like this:

    $stmt = "SELECT * FROM users WHERE email = '" + $_POST["email"] + "' and password = '" + $_POST["password"] + "'";

The WAF filters out requests of the type:

    curl -i http://vuln.test/app/foo.php --data-urlencode "email=a" --data-urlencode "password=b' or 1 union select 0, 0, 0, 0"

I'm looking for a feature in sqlmap that would allow for injecting the parameter this way:

    curl -i http://vuln.test/app/foo.php --data-urlencode "email=a' or 1 union /*" --data-urlencode "password=*/ select ..."

**Comment by stamparm** [comment]
This is not practical for automation. Your case is an obvious one which could bypass WAF, but what about other SQLi types/payloads. Each WAF has it's own blacklisted sql formations. If you have e.g. only two parameters for usage, then you are pretty limited here. Also, subqueries would be detected because you can't split those in unlimited number of parameters. Closing rhis down as this is not something for automation
