### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by fredhagedorn** [sqlmapproject/sqlmap#2211]
(1) Make the tamper scripting use as "suggestion" (just like when sqlmap "sugests" that certain database is mysql. (2) in real time log/grab/trace ONLY the data sent and received (and respective queries) from sqlmap itself. (3) translate the whole program.
...
Stampar, my man (I salute others who reads this page, but, you know, stampar helps the fuck out of everybody here), I saw your minnor updates made in virtue of my previous issue request. Thank you again. Lets go: The important parts are written in bold. The silly content isnt "bolded".

**Dude, theres a way to see, in another terminal/screen (or through any other way) a real-time ("live") of the queries used by sqlmap?**

Yeah, I know, theres -v (already read manual 10²³ times), but, you see, its always damn fast, no matter how many threads I put. In the other hand, if I use `--fresh-queries > fresh_queries_dude.txt` I cant see nothing from terminal.

I'm not a programmer (I dont have time to even do take a dump [not the sql one], imagine reading those python books), I may be noobing this important session, but I googled everywhere and I only face noob people too, like the average sqlmap user:

>cmd.exe
>cd C:/HACKSTUFF/sqlmap
>sqlmap.py --url
> --current-db
> -D
> -T
> -C
>--random-agent.
>???
>feels like mitnick when he hacked the moon

**Therefore, I need you help/advice.**

Another suggestion/issue(?):

**I and probably 99,9% of the dudes who learn tamper usage in cockroach-panic mode...**

`--tamper=i_have.py,no_ideia.py,what-iamdoing.py,but_tampers_are_cool.py`
>gets 404
>random-agent  or --tor
`--tamper=i_have.py,no_ideia.py,what-iamdoing.py,but_i_know_tampers_can_do_magic,just_dont_know_how_it_works` (just)
>gets 406 now
>gets mad
>google "how to use sqlmap tampers for g-d sake"
>no proper result

We (at least me, fredhagedorn) can only "learn" how to use few of tampers because (at least in my case, case of fredhagedorn) I go full maniac and open the source code of everything and tests thousands of URLs manually (yeah, my ctrl+shift+c/v fingers arent in good FORMAT lol).

## **Can you, as the big boss of sqlmap, do something like a guide or - and it would be WAY BETTER - give "suggestions" to user (just like when sqlmap "suggets" that certain website have mysql database, sqlmap would prompt like "in this case, if you face data retrieval problems, rerun the tests using the --tamper=varnish,charencode switch"). Do you get it?** 

**By the way, I have some interest in translate the entire sqlmap structure. It would be useful?**

**Comment by stamparm** [comment]
In no particular order:

* auto-tampering or tamper-suggestion is hard for implementing in meaningful matter because of multiple reasons. First one is the most obvious one. Today's protections are really good at "protecting". So, there is no silver bullet approach. Also, automating stuff for people that are not keen on bypassing WAFs is like giving people a gun so they could shoot themselves into the leg. The other reason why is it hard is because if there is a protection and you want an automated tool (in this case sqlmap) to recognize both the SQL injection and how to bypass the protection you will end up in M*N number of required requests that would need to be done for this to work. At the end, you would end up with zillion requests per parameter. I could do some basic stuff (like suggesting some generic tamper scripts) but believe me, as said, todays protection are really good - at least in preventing automated tools
* personally, when I spot a protection I am always trying to bypass it manually. Also, the final solution is always something that is kind of hard to be used from sqlmap or any other tool.
* I am not sure what you meant with "translate the whole program"?
* If you want to `log/grab/trace` sqlmap traffic you can do it in multiple ways: A) `--proxy` with Burp in between; B) `-t traffic.txt` inside of file `traffic.txt` you should see the traffic in real-time (new requests/responses are appended automatically); C) `-v 5` this will show you all `[PAYLOAD]`/`[TRAFFIC OUT]`/`[TRAFFIC IN]` data. If it's blazing fast, you can always pipe it through `less` (e.g. `python sqlmap.py -u ... -v 5 | less`); D) use `grep` to get only the data you need from sqlmap's output (e.g. `python sqlmap.py -u ... -v 3 | grep PAYLOAD` will show you only the payloads being sent)

**Comment by fredhagedorn** [comment]
By "translate the whole program" I mean translate the lines shown when we execute sqlmap. Sqlmap itself, you know? Screenshot related. If you want, I can start doing it (we speak poortuguese here; i'm brazilian like the jiu-jitsu you fight). Just give me the tips (which files I need to access for translation, e.g.). Very very thanks for your support.

![screenshot](https://cloud.githubusercontent.com/assets/22554017/19132492/0e8b34f8-8b2a-11e6-831f-70bfee78434a.png)

**Comment by SweetSoul** [comment]
I think it's not a good idea... If anyone want to use sqlmap (s)he has to know english... It is the base for the knowledge on internet... I'm brazilian too but i think that this tool needs to be a Lil bit difficult to at least freighten some lamers.

**Comment by fredhagedorn** [comment]
Yeah, you do have a point. We already have a a shitload of c*ckscuckers who screws our job with sqlmap being a non-gui software english-only. Imagine if it would be more easier.

Anyway, congrats to stamparm, the most based croatian dude since... Another based croatian.
