### ISSUE TITLE
Restore Scan after system crash and other questions

### ISSUE THREAD

**Issue by JonhSilver** [sqlmapproject/sqlmap#2308]
Hi,
I'm very grateful to you for your amazing product.
Uncomfortable indicate to some little inconvenience. Sorry for that.

Sorry but i cant sent logs beacause system was crashed and i cant save anything.

Error based injection.
Always run to system crashes on windows Xp, 7, 8 no matter.
DDR RAM 32GB
Crashes beacause of using too much memory. Yesturday crashed by memory fault only python today was crashed all windows sistem with error of memory  leakage and BSOD.

In this case wich causes very often can you please do some changes to sqlmap to alleviate the consequences of system failure.
1. Restore previous scans ( i think must be log file where to save each FULL scan starting string with all parameters such as "python.exe sqlmap/sqlmap.py -u "www.example.com" --batch --random-agent --dbms=mysql -D database1 -T users --dump -dump-format=htm" beacause target.txt is not helpful because do not contains all provided parameters and sqlmap ( in case of typed different parameters from previous scan) start new target scan but not restore previous scan from crashed point. But if run sqlmap with last scan typed strinf=g with full parametrs sqlmap restore previous session.
2. Purge session.sqlite to dump folder each 10 min,  as i think this is cause of memory crashes
3. Have to understand tampers scripts workout? when i must use which tamper? is that exist some common combinationt of tampers scripts? Why not to do new switch like --common-tampers ? it be very useable!
4. Have you planing to do GUI for Sqlmap? Maybe reward could be a decisive factor in this direction? I am ready to participate.

Thank you for all you’ve done

**Comment by stamparm** [comment]
This is going into wrong direction. Purging of session.sqlite is absolutely
not an option. You are the first that is asking for this. All info is
stored there for normal resumal of session.

**Comment by stamparm** [comment]
Please inspect what's causing the BSOD. sqlmap is made to not easily eat
the 32GB of RAM. Also, Python can't cause BSOD. As said, please do a proper
inspection before blaiming on sqlmap.

On Dec 17, 2016 10:32, "JonhSilver" <notifications@github.com> wrote:

Hi,
I'm very grateful to you for your amazing product.
Uncomfortable indicate to some little inconvenience. Sorry for that.

Sorry but i cant sent logs beacause system was crashed and i cant save
anything.

Error based injection.
Always run to system crashes on windows Xp, 7, 8 no matter.
DDR RAM 32GB
Crashes beacause of using too much memory. Yesturday crashed by memory
fault only python today was crashed all windows sistem with error of memory
leakage and BSOD.

In this case wich causes very often can you please do some changes to
sqlmap to alleviate the consequences of system failure.

   1. Restore previous scans ( i think must be log file where to save each
   FULL scan starting string with all parameters such as "python.exe
   sqlmap/sqlmap.py -u "www.example.com" --batch --random-agent
   --dbms=mysql -D database1 -T users --dump -dump-format=htm" beacause
   target.txt is not helpful because do not contains all provided parameters
   and sqlmap ( in case of typed different parameters from previous scan)
   start new target scan but not restore previous scan from crashed point. But
   if run sqlmap with last scan typed strinf=g with full parametrs sqlmap
   restore previous session.
   2. Purge session.sqlite to dump folder each 10 min, as i think this is
   cause of memory crashes
   3. Have to understand tampers scripts workout? when i must use which
   tamper? is that exist some common combinationt of tampers scripts? Why not
   to do new switch like --common-tampers ? it be very useable!
   4. Have you planing to do GUI for Sqlmap? Maybe reward could be a
   decisive factor in this direction? I am ready to participate.

Thank you for all you’ve done

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sqlmapproject/sqlmap/issues/2308>, or mute the thread

**Comment by JonhSilver** [comment]
I just start sqlmap for previous session, and sqlmap start dump from begining but not from last position. in log file start filling with duples from database. Before crash sqlmap dumped 576000 strings order by id, now it show dumping from id 1.  So after crash i need wait for 3 days again for dump thoose 576000 strings. (((

**Comment by Ekultek** [comment]
Okay, @stamparm I don't mean to jump in. Here's the thing @JonhSilver, it is impossible for Python to cause a BSOD. If Python eats to much memory it will stop with a `memory error`. A BSOD is caused by the computers system files not calling upon one another correctly.

For instance let's say you have 376gh.dll that calls upon line 7 in 027.dll if for some reason the first file calls line 8 instead of line 7 the system will crash. What can cause this? Everything from updates to viruses, my advice to you is to start scanning your computer, or reimage it. Sqlmap is not the cause of your computer crashing.

**Comment by z3ro** [comment]
any  update for this ?
am also looking for same thing
