### ISSUE TITLE
Fingerprint-only mode?

### ISSUE THREAD

**Issue by djmally** [sqlmapproject/sqlmap#2405]
Is there a way to run SQLMap in a fingerprint-only mode? I'd like to do some quick large-scale DB fingerprinting, but it seems like `sqlmap --fingerprint -u <url>` does fuzzing first, and then fingerprints at the very end. What I'd like is for the fingerprinting step to come first, and for the fuzzing process to be skippable, as all I need/want is the fingerprint, not to launch attacks. Is this possible to do in SQLMap as-is, and if not, can someone recommend a different tool to use?

**Comment by stamparm** [comment]
Fingerprint doesn't work without a successful detection of SQLi. Hence, your question doesn't make any sense. You are most probably trying to parse DBMS error messages, but sqlmap can't only do that because those error messages are not proof of SQLi. Take a look into xml/errors.xml and make your own solution
