### ISSUE TITLE
Bug when uses single quotes in xml payload

### ISSUE THREAD

**Issue by SpotBR** [sqlmapproject/sqlmap#2441]
## What's the problem (or question)?
I have a xml payload file that replaces the default blind payloads, when i put single quote in [RANDOMNUM] the random num loses the single quotes and becomes a giant hex like **0x33313436** on logged payloads cases.

## How can we reproduce the issue?
**1. Uses this blind papyload xml:**
`http://pastebin.com/RwPCaDbR`

**2. Use VERBOSE 6 in a command like:**
`sqlmap --technique=B --code=520 --threads=10 -r request_buscar --prefix="asdds'" --suffix="#" --dbs -v 5 --dbs --risk=3 --level=2`

**3.Wait for OR CASES on terminal and look:**
http://i.imgur.com/pxflTta.png

## What are the running context details?
**Client OS** Kali Linux 4.8
**Python version** Python 2.7.12
**SQLMap version** SQLMap 1.1.3-11
**Installation method** tar.gz

**Comment by stamparm** [comment]
`and becomes a giant hex like 0x33313436` <- because of this I'll close this as invalid. Please don't run sqlmap if you don't know basics of SQL or how any DBMS works (e.g. MySQL or MsSQL). That is `giant hex` is a string encoded to its hexadecimal form. That's what sqlmap usually does. If you want to turn it off you can use `--no-escape`.
