### ISSUE TITLE
Support for custom script after the page was loaded

### ISSUE THREAD

**Issue by tampe125** [sqlmapproject/sqlmap#2553]
Hello,

I'm currently having an issue with a site that has some antispam protection: after X requests, a javascript script is presented to the page, updating the cookies. Then the page reloads.
Now, I know how to parse it and extract the new cookie value, however I'll need the ability to fetch the output and update SQLmap global options, so we could be ready for the next request.

Any ideas on this?

**Comment by stamparm** [comment]
Regular way how to evaluate some custom code is through `--eval`, though, it is meant to be evaluated before the request itself. Also, accessing internals in that case (e.g. through provided dictionary `_locals`) is really hard for normal user.

Now, evaluation of code **after** the response itself, like you require is currently not possible. Even though your request makes sense, IMO users wouldn't touch this kind of mechanism because it would be too hard for them to handle it (in plainspeak, I doubt that such feature would be used by anyone as it would require proper knowledge of internal mechanisms).

Because of given reason I would like to point you to the `lib/request/connect.py` itself so you would do the per-case adjustment yourself (e.g. https://github.com/sqlmapproject/sqlmap/blob/master/lib/request/connect.py#L1222 would be a nice place to do that). At that place you could parse the response `page` and store cookie value(s) for later usage

**Comment by tampe125** [comment]
Great, thank you very much for the hints.
I can simply fork and apply your suggestions. Thanks again!
