### ISSUE TITLE
triple encoding

### ISSUE THREAD

**Issue by z3ro** [sqlmapproject/sqlmap#2594]
hello
i have the vuln link with 3 times encoded with base64 
any idea to set the temper to make 3 times encoding for the query ?

**Comment by stamparm** [comment]
Idea goes like this:

0# You should provide that same parameter value in (triple-)unencoded form (e.g. if original was `...&foo=V1cxR2VRPT0=` then provide it like `&foo=bar`).

1# Then, you should either modify the  `tamper/base64encode.py` or create new (e.g.) `tamper/triplebase64encode.py`. Inside of it instead of original `base64.b64encode(payload.encode(UNICODE_ENCODING))` do the `base64.b64encode(base64.b64encode(base64.b64encode(payload.encode(UNICODE_ENCODING))))`.

2# At the end run the sqlmap like: `... --tamper=triplebase64encode -u "...&foo=bar"`
