### ISSUE TITLE
Unknown database and columns!

### ISSUE THREAD

**Issue by MrDude112** [sqlmapproject/sqlmap#2609]
Hey
First of all big thanks for Sqlmap teams,
My question is when i try to scan a website to access database it showing a unknown database or unknown columns, so can i have some answer about it why it hapining like this and it possible to get a correct name of Databse or columns?

Thanks

**Comment by stamparm** [comment]
This can be caused by lots of problems. For example, false-positive SQLi
from the beginning (rerun with --flush-session), web application or server
protection, dynamic content in case of boolean SQLi, network latency in
case of time SQLi, generic problems with --tor/--proxy, etc.

You should inspect payloads with -v 3 and try to rerun in e.g. browser, or
inspect traffic with -t traffic.txt and rerun problematic requests with
Burp.

Bye
