### ISSUE TITLE
Dumping Error of SQLMAP

### ISSUE THREAD

**Issue by smfai200** [sqlmapproject/sqlmap#2655]
I have a Table to Dump that is:
Table: Users
[20 columns]
+--------------+---------+
| Column       | Type    |
+--------------+---------+
| CampId       | bigint  |
| ComsisID     | varchar |
| CVPath       | varchar |
| Department   | varchar |
| Designation  | varchar |
| Did          | bigint  |
| Email        | varchar |
| Enable       | bit     |
| FirstName    | varchar |
| FolderPath   | varchar |
| IsSubscribed | bit     |
| LastName     | varchar |
| Login        | varchar |
| Password     | ntext   |
| PicPath      | varchar |
| PicPath2     | varchar |
| Priority     | float   |
| Status       | varchar |
| Uid          | int     |
| UserType     | varchar |
+--------------+---------+
You see all others are Fine but Password Column shows Unicode such as "Ä¢ÄÄÄÄ‘ÄƒÄ–Ä‘Å†". The Column type is ntext and i have already tried --binary-fields and --hex and --no-cast but no luck!

**Comment by stamparm** [comment]
It is a binary data. `--binary-fields` should retrieve it's hexadecimal representation. Afterwards it is up to you to crack it with some other tool. 

Also, writing `--binary-fields... but no luck` doesn't add anything to this issue because you failed to explained what you think got wrong.

Anyway, getting junk in password field is NORMAL and you should treat it as a binary data. Not sqlmap's issue
