### ISSUE TITLE
MAX NUMBER OF THREADS

### ISSUE THREAD

**Issue by FailGecko9800** [sqlmapproject/sqlmap#2676]
hi how are you. i am a big fan of your program SQLMAP

i was wondering if you could tell me where i could find the threads bit of the code because i want to edit the code to change the maximum number of threads to around 15 so it runs faster, but i can't seem to find the right file or bit of code to edit to change that

can you please help me

Thanks

**Comment by fiht** [comment]
Hi. Welcome to gayhub.
Maybe I could tell you how to solve this type of question.
## first
first we make the programmer crash.
```
./sqlmap.py -u "http://localhost?fsdf=1" --threads 100
```
sqlmap will exit and with some log. like
```
➜  sqlmap git:(master) ✗ ./sqlmap.py -u "http://localhost:1212?fsdf=1" --threads 100
        ___
       __H__
 ___ ___[.]_____ ___ ___  {1.1.7.31#dev}
|_ -| . ["]     | .'| . |
|___|_  [(]_|_|_|__,|  _|
      |_|V          |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting at 14:33:24

[14:33:24] [CRITICAL] maximum number of used threads is 10 avoiding potential connection issues

[*] shutting down at 14:33:24
```
## Then 
Then we use the log to find which code logged this.
so we search the log in this project
![image](https://user-images.githubusercontent.com/15059493/29993534-4fe20d38-8fec-11e7-93e2-8e62e1adc7c8.png)
We could guess we could inc the ```MAX_NUMBER_OF_THREADS ``` in the setting.conf to solve this (poor in English, i believe you know what i mean). 
Because it is a open source project, we can also know how the which code detect the maxthread. so we can use the search result[1]. and linked to this [code](https://github.com/sqlmapproject/sqlmap/blob/cb2258fea427ecf19c0bcbd7efca67867bfa6cc1/lib/core/option.py#L2469). 
read the code youself and make you own sqlmap.
# At Last
Welcome to gayhub!

**Comment by stamparm** [comment]
As @fiht stated, setting is called `MAX_NUMBER_OF_THREADS` and it is located in `lib/core/settings.py` (https://github.com/sqlmapproject/sqlmap/blob/415ce05a2fc30908e4a911c21c3c52a53a333bc6/lib/core/settings.py#L351). Just change that value at your side and that should be it.
