### ISSUE TITLE
--os-shell switch

### ISSUE THREAD

**Issue by MrShhh** [sqlmapproject/sqlmap#2704]
## What's the problem (or question)?
Does --os-shell switch can only be used when the current user is the DBA?

**Comment by stamparm** [comment]
There are lots of planets that need to be aligned for this to work:

1) If user is not DBA then most probably he won't have access to DBMS file writing functions (e.g. https://stackoverflow.com/a/30359605)
2) After 1) there is also an issue of current-system user (e.g. `mysql` <- doesn't have anything to do with DBA) or what are his SYSTEM permissions
3) File has to be written inside www-server reachable structure (e.g. `/var/www`) or otherwise there is no point to write to some random location
4) If 1) and 2) and 3) are fulfilled (rarely lately) you'll be able to use `--os-shell`

**Comment by stamparm** [comment]
Pretty much yes. Maybe you could get lucky with `--file-read` :)
