### ISSUE TITLE
[CRITICAL] connection reset to the target URL. sqlmap is going to retry the request(s)

### ISSUE THREAD

**Issue by FailGecko9800** [sqlmapproject/sqlmap#2707]
Hi how are you all, i hope you all are well.
i am a big, big fan of SQLMap and enjoy using it, i am now using tamper scripts and invalid strings and have managed to teach myself advanced SQLMap

but i am having one issue, i was wondering if there is a way to bypass "[CRITICAL] connection reset to the target URL. sqlmap is going to retry the request(s)" with tamper scripts or some other way with SQLMap

the command i am using is: "sqlmap -u www.example.com/content.asp?Document_ID=2 --random-agent --threads=5 --risk=3 --level=5 -v2 --tamper=between,informationschemacomment,bluecoat,charencode --drop-set-cookie --fresh-queries --binary-fields -identify-waf --text-only --titles --invalid-string --invalid-logical --invalid-bignum --dbms="microsoft access" --hpp --parse-errors --no-cast --no-escape --ignore-proxy -o --dbs
"
also i was wondering if i could hire one of the developers to teach me some python programming because i must say that your work is professional and i look up to that sort of stuff

Thanks again everyone for the support
i hope to hear back soon
Thanks :) :) :)

**Comment by stamparm** [comment]
In most situations "connection resets" are caused by active defense equipment (e.g. WAF/IPS) blacklisting recognized malicious requests. Also, in rare situations you can do anything automatically without taking a look deep-inside (e.g. Burp) what are the rules of the protection and how to eventually bypass it.

As of python programming teaching, you could contact me privately at `miroslav@sqlmap.org`, though I am pretty tight with time
