### ISSUE TITLE
sqlmap -g (google search) not working using socks/proxy BUT working using browser

### ISSUE THREAD

**Issue by jmcausing** [sqlmapproject/sqlmap#2753]
hey guys,

I tried using proxy / socks using sqlmap map -g google search and it detects unusual traffic.

but when I use the same proxy / socks in my firefox using the same keyword, it works and I am able to see the search results from google.

is there any solution for this?

**Comment by jmcausing** [comment]
here is the screenshot about my issue above: https://www.screencast.com/t/gyXMCwV0

**Comment by Ekultek** [comment]
Use a different search engine, or a different proxy

**Comment by jmcausing** [comment]
@Ekultek  the problem is that using the same proxy, firefox is able to use the search but sqlmap cannot.

**Comment by Ekultek** [comment]
@jmcausing No the problem is that you're trying to connect to Google via a thirdparty program that doesn't use Google's API therefore Google is picking up on the weird connections and see's your proxy. Using a proxy through a web browser is different then using a proxy through a program IE sqlmap.

Sqlmap can fscan using DDG also, so I'd suggest you use DDG instead of Google if you're trying to run behind a proxy. DDG isn't going to try and block you, but Google will because they want to know who you are.

**Comment by jmcausing** [comment]
@Ekultek , so sqlmap automatically runs DDG when google fails. It selected [1]  as default and that is DDG but it still goes for google. please see screenshot: https://www.screencast.com/t/IVdOqTKQR5

**Comment by stamparm** [comment]
@jmcausing first of all you haven't posted anything useful here (e.g. options and switches).

Also, have you considered that user agent could be different inside sqlmap than inside Firefox?
