### ISSUE TITLE
[BUG] 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by AdaptCharm** [sqlmapproject/sqlmap#2852]
I'll try to make this as brief as possible, mainly because it's not a critical bug.

**Screenshot:** [https://i.gyazo.com/3a9b0391df7b5e3d6f78f4b6a0d3ce39.png](url)

**Error msg:** [09:11:41] [ERROR] thread 2: 'NoneType' object has no attribute 'lower'

**Comment by stamparm** [comment]
Thank you for your report. I went through all `lower()` usages and can't find the one causing this. Are you using the latest revision and is this something that happens regularly on your side?

**Comment by AdaptCharm** [comment]
@stamparm Yep, I'm using the latest revision. This usually happens every single time upon starting a new sqlmap scan.

The command used to run sqlmap: `python2 sqlmap.py -u "url here" -D "database name here" -T "table name here" -C "column names here" --dump --eta`

Here's another screenshot: [https://i.gyazo.com/9478cb24a070fb895c4a7577335a4369.png](url)

**Comment by stamparm** [comment]
Please pull the latest revision (at least `1.1.12.33#dev`) and rerun with `-v 2`. You should get a traceback exception message along with the "thread error" you reported. Please copy paste it here so I could see what is causing it.

**Comment by AdaptCharm** [comment]
@stamparm I followed your instructions, however, I didn't get any traceback exception message at the end.

**Comment by stamparm** [comment]
I pushed one more patch, but I am pretty sure that even with the latest revision you should get the error traceback just after that `'NoneType' object has no attribute 'lower'` message. By traceback I mean the exact location inside the sqlmap's python code where the error is occurring.

Could you please (instead of git or manual patching) download the zip from [here](https://github.com/sqlmapproject/sqlmap/zipball/master) and use that version?

**Comment by stamparm** [comment]
Closing due to lack of response
