### ISSUE TITLE
 How can I continue ?? 

### ISSUE THREAD

**Issue by xdevil68** [sqlmapproject/sqlmap#2902]

**Comment by stamparm** [comment]
short: I would say that you can't continue
long: for start, you are using a long list of unrelated tamper scripts. i am not sure how this can work in the first place. you could be dealing with the false-positive (rerun everything with `--flush-session`). then, you are sending invalid parameter values and being warned by the sqlmap. also, you are getting HTTP code 400 which could be a sign of invalid HTTP requests in the first place (maybe because of tons of tamper scripts used)

anyway, please continue the target assessment manually as sqlmap won't be of much help here
