### ISSUE TITLE
database problem

### ISSUE THREAD

**Issue by DeAdHaCkErZ** [sqlmapproject/sqlmap#2930]
i have used sqlmap and after injection i have 1 database 

jumboco_)(*&^%$#@!jumbo

and when run 

python sqlmap.py -u "https://website.com/store/index.php?route=product/product&product_id=5120" -p product_id --random-agent -D jumboco_)(*&^%$#@!jumbo --tables

i have this problem

bash: !digits: event not found

**Comment by stamparm** [comment]
You can't just put random characters to bash command line. Enclose those with single quotes (e.g. -D '.....')

**Comment by DeAdHaCkErZ** [comment]
It's work thanks alot but after that i put --tables not working or any other command

**Comment by stamparm** [comment]
Because it doesn't look like a proper database name. If you are dealing with boolean-based blind or time-based blind you could rerun with `--fresh-queries` the database name retrieval part. Also, in case of time-based blind you'll have problems if any proxy and/or tor is in between (I don't know the situation as you haven't stated in the first place).

Anyway, you should debug on your own what is going on further as the original issue is resolved
