### ISSUE TITLE
Inject into Auth Basic

### ISSUE THREAD

**Issue by z3ro** [sqlmapproject/sqlmap#3052]
## How to inject into the auth basic ?
tryed to inject via --auth-type=BASIC --auth-cred=*:abc123 
but does not help.
i would try to use -r file but dont have any idea how to do base64 encode for *:pass in auth basic and make sqlmap understand my request.

**Comment by stamparm** [comment]
There is really no easy way how to do this. Also, don't expect automated support from sqlmap for this.

1) Though, I'll left you here how you could do it with `--eval` in case that you wanted to inject into the `password` part:

`python sqlmap.py -u ... -H "Authorization: Basic username:password*" --eval='_=(_locals["auxHeaders"].get("Authorization") or _locals["headers"]["Authorization"]).split(":", 1);_[1]=_[1].encode("base64").replace("\n", "");_locals["auxHeaders"]["Authorization"]=":".join(_)'`

2) In case that you wanted to inject into the `username` part you could just use something like this:

`python sqlmap.py -u ... -H "Authorization: Basic username*:cGFzc3dvcmQ="` (Note: `cGFzc3dvcmQ=` is base64 encoded value for string "password")

**Comment by z3ro** [comment]
when trying eval.
[22:12:33] [INFO] testing connection to the target URL
[22:12:33] [CRITICAL] an error occurred while evaluating provided code ('EOL while scanning string literal')

and when try to inject user.
[22:14:01] [INFO] testing connection to the target URL
[22:14:01] [CRITICAL] not authorized, try to provide right HTTP authentication type and valid credentials (401)
[22:14:01] [WARNING] HTTP error codes detected during run:
401 (Unauthorized) - 1 times

**Comment by stamparm** [comment]
1) EOL is because you've mistyped something. I've just copy pasted that piece of code I wrote and could get that. Find screenshot attached. Also, Google for that same error and you'll see what is causing this kind of error
2) You should also use `--ignore-code=401`

![1](https://user-images.githubusercontent.com/921555/38783744-ac980192-4106-11e8-9280-38a0cb959f86.png)

**Comment by 2d4d** [comment]
@stamparm 
this wouldn't work because the base64() should be around username:password (https://en.wikipedia.org/wiki/Basic_access_authentication#Client_side)

but I have trouble figuring out how to do it properly, where does the magic happen, that each sql-injection string is inserted in the --eval? (not documented in https://github.com/sqlmapproject/sqlmap/wiki/Usage)
