### ISSUE TITLE
question about dаtа uрdate

### ISSUE THREAD

**Issue by shadowfolder** [sqlmapproject/sqlmap#3183]
del

**Comment by AmericanY** [comment]
sometimes i feel that sqlmap users speaking different English language.

`Can i change mysql columns data` what?

well, let's say you did run sqlmap against one target and sqlmap detected ( Boolean, Time Based And Union Query)

Sqlmap by default gonna ask you about which one you are preferring to use in order to retrieve the information ! otherwise you can be more specific and just proceed with `--technique=THE SQL INJECTION TYPE YOU PREFER `
