### ISSUE TITLE
Dump without fresh queries

### ISSUE THREAD

**Issue by shadowzoom** [sqlmapproject/sqlmap#3189]
Here is example:
I've dumped 1000 rows from table.
After some days this table already  has 1500 row, but when i'm trying to run dump with sqlmap, it's shown oldest value (1000 rows) when there is actually 1500 row. But dump again 1000 rows + new 500 rows will take much more time, rather than just dump new 500 rows.
As i see hardfork is --dump --start=1000, but would be great when every --dump sqlmap will be check numbers of rows

**Comment by stamparm** [comment]
`--dump` is problematic on "dynamic" tables. For example, what if 500 records are being deleted while 677 new are being added? As you've noticed you can use `--dump --start=...`. In case that I include the check for a table count (disregarding the stored session value) somebody else will nag what the session value is not being used. Also, in case that the new table count is different than the old one what should sqlmap do in your case?

As said, you already have mechanism to "manage" it by yourself.

**Comment by AmericanY** [comment]
@shadowzoom 

1- 
![42886712-8c5dafca-8aa4-11e8-8a41-d7744d89d7c4](https://user-images.githubusercontent.com/27644047/43040889-d6704d4e-8d50-11e8-86e4-d11fbb0a569e.png)

2- point #1 is important in order to know which database manager you dealing with so next time you need to mention all required information.

3- that's completely not a `sqlmap` issue, you need to manage that by yourself. as you know the old count and the new count so you can just dump the new from where you have end. either by `--start=` or by `sql query` and that's depending which database manager you deal with.

@stamparm `no further response needed -- to be closed`
