### ISSUE TITLE
Sqlmap Dumping Question

### ISSUE THREAD

**Issue by fantasy04** [sqlmapproject/sqlmap#3199]
Hello,

I am quite new to Sqlmap. I am still learning and hoping someone could explain about this problem I am having.

* Is there any way we can get sqlmap to give output file even when the dumping progress have not finished yet. Is there any way to access the "Session File" and retrieve the data inside by ourselves with correct dumping format. "example: user:password"
* I see the "Session Sqlite" file, Supposed I close the sqlmap dumping session. If I want to start a new session and expect sqlmap to resume from the last entry. What should I do? or how to use command.
* About Threads, Is there any risk of crashing the target site server if we use Threads=10? 
 
Like I mentioned above, I have not much experience with Sqlmap, please help put some light into these issues.

Thanks in advance for help and feedback,

Regards

**Comment by AmericanY** [comment]
@fantasy04 Welcome to `sqlmap`, First of all you need to know there's a full description of `How to use sqlmap` described here [https://github.com/sqlmapproject/sqlmap/wiki/Usage](url)

So to not waste our time, kindly try to ask a question which is not listed on the above link so it's will be a `useful` question.

Regarding your points:

- By default you can see the output on the screen while dumping the data from the server and it's completely stored inside `log` file inside each target folder. 

- Sure you can read session.sqlite  using `sqllite viewer`

- `sqlmap` by default gonna resume from where it's end. unless if you used `--fresh-queries` or `--flush-session` so it's gonna start from the beginning. Therefor `sqlmap` can Load session from a stored `(.sqlite) file` by using `-s SESSIONFILE NAME`

- `--threads=` indeed it's according to the server response and if there's any WAF protection or not, Also it's depending the internet connection of the server you Pentresting the target from it. so that's require user knowledge and following up the target response while increasing `threads` and checking if the connection got dropped or How the `WAF` acting.

Hopefully you do have enough answer for your `questions`


@stamparm `NO FURTHER RESPONSE NEEDED. To Be Closed`

**Comment by stamparm** [comment]
`Is there any way we can get sqlmap to give output file even when the dumping progress have not finished yet. Is there any way to access the "Session File" and retrieve the data inside by ourselves with correct dumping format. "example: user:password"`
- nope. Lots of formatting of the dumped data depends on the whole table dump. Eventually I'll make a dirty dump of partial data (Issue $516), but will immediately close all further user Issue reports of not-so-nice formatted partial table dump(s)

`I see the "Session Sqlite" file, Supposed I close the sqlmap dumping session. If I want to start a new session and expect sqlmap to resume from the last entry. What should I do? or how to use command.`
- just repeat the last command. sqlmap should automatically resume outputs that it got the response from the target. For example, in case of a dump, if you Ctrl-C break and resume afterwards, sqlmap should at least contain responses to the queries/payloads that were being used during the previous dump session.

`About Threads, Is there any risk of crashing the target site server if we use Threads=10?`
Most probably you won't crash the web site, but you'll get "unstable" responses, particularly in case of ASP(.NET)/MSSQL/IIS platform which doesn't tolerate too many opened connections. By "unstable" responses I mean that you could get lots of WARNINGs along with couple of `None`/`NULL` values
