### ISSUE TITLE
Confused about errors when trying to upload stager

### ISSUE THREAD

**Issue by R4zzM** [sqlmapproject/sqlmap#3232]
## Problem
I'm currently learning about SQL Injections and my previous experiences with SQL is limited. Please forgive any misunderstandings and misuse of terminology on my part. 

I have managed to find an injection point in a site with a MySQL dbms. Using this I can use sqlmap to read anything in the database via the --sql-query option and to read files located on the host via --file-read. What I really want to do run remote commands. If I try to upload a backdoor "manually" via --file-write, sqlmap will reply with an error saying it is not possible due to the type of injection:

`[ERROR] none of the SQL injection techniques detected can be used to write files to the underying file system of the back-end MySQL server`

Okay, fair enough.
Now I try with --os-shell/--os-cmd which also fails saying that the stager wasn't uploaded (too many 4xx/5xx responses). When observing with -vvvvv I can see in the responses that sqlmap tries to run an SQL-command that results in an SQL syntax error which looks like (html formatting removed and a,b,c,d and e are not the true names. Values are real though):

```
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '1 INTO OUTFILE '/var/www/html/php/tmpuhcem.php' LINES TERMINATED BY 0x3c3f706870' at line 4. SQL Request
UPDATE users SET
        a = '1',
        b = '1',
        c = '1' LIMIT 0,1 INTO OUTFILE '/var/www/html/php/tmpuhcem.php' LINES TERMINATED BY 0x3c3f...<stager payload>...3e0a--  AND 'zYHQ'='zYHQ',
        d = '1'
        WHERE e = 3441
```

Now I'm confused (partly because I don't really understand the SQL query, to me it doesn't look valid). I'm thinking:
- If the query is indeed valid, is this a bug in sqlmap (very unlikly, as the tool seems very solid) or am I doing something fundamentally wrong?
- If this is not a valid query, why does sqlmap try to run it? Wouldn't it be a more consequent behavior to report an error similar to when trying to upload a file? In that way it wouldn't be confused with permission errors etc.

Regards,
Rasmus

## Details
* Installation method: Pre-installed (would use apt to update).
* Client OS: Kali linux
* Program version: 1.2.8 
* Target DBMS: MySQL 
* SQLi techniques found by sqlmap: "Error-based" and "AND/OR time-based blind"

**Comment by stamparm** [comment]
* ```If the query is indeed valid, is this a bug in sqlmap (very unlikly, as the tool seems very solid) or am I doing something fundamentally wrong?```
That query is not valid. sqlmap tries to inject into the underlying `UPDATE` statement which doesn't accept `LIMIT 0,1 INTO OUTFILE` formation (coming from sqlmap). Not sqlmap's fault as it doesn't "know" the underlying SQL statement nor it can change it whatsover (`UPDATE` is used by the vulnerable application itself)

* ``` If this is not a valid query, why does sqlmap try to run it? Wouldn't it be a more consequent behavior to report an error similar to when trying to upload a file? In that way it wouldn't be confused with permission errors etc.```
Because sqlmap doesn't know that underlying injectable statement is `UPDATE...SET...`. It tries to inject to whichever statement it originally affected by the SQL injection vulnerability. Now, you can ask for sqlmap to understand the underlying statement and say that it should KNOW that from the beginning (e.g. because of the error message) and I'll just reply that this is a futile job for the majority of cases.

p.s. you are telling that you are "confused" about the sqlmap's explanation what was the most probable cause (permission problems), but that is just that. Most probable cause. You can always run with `--parse-errors` to see what could potentially go wrong at the other end. Just remember that you'll most likely not get any useful error message in the first place.

**Comment by ahmet732** [comment]
I fixed the issue after reading the post below:

https://www.willhackforsushi.com/?p=581
