### ISSUE TITLE
Support H2 DBMS

### ISSUE THREAD

**Issue by jzheaux** [sqlmapproject/sqlmap#3283]
It would be nice if sqlmap supported [H2](http://www.h2database.com/html/main.html).

H2 is a DBMS that was developed by the same individual that developed HSQLDB.

Current fingerprinting strategies pin H2 databases as being PostGre, but the enumeration strategies don't work because H2 doesn't have the `CURRENT_SCHEMA` function.

I've also tried applying the HSQLDB enumeration strategies without luck.

**Comment by stamparm** [comment]
Any way to have any vulnerable point to base the development? VM or something? Blind development on non-widely used DBMS is a no go

**Comment by ron190** [comment]
PHP test bed scripts for those dbs can be found here:
https://github.com/ron190/jsql-injection/tree/master/web/test-bed/others

Injection models for those dbs:
https://github.com/ron190/jsql-injection/tree/master/src/main/java/com/jsql/model/injection/vendor/xml

**Comment by stamparm** [comment]
@ron190 by the way, have you ever managed to connect to H2 with your scripts? Looking into those seems to me just like a reference on how IT should be done. For example, you use the `PJBS.php` which by default has a garbage settings for PgSQL connection inside its configuration (and I can't seem to find where you are changing any of those).

**Comment by ron190** [comment]
My apologies too.

Patronizing others as usual, though totally expected from you so not a big deal, but kind of ironic in that situation.

Whatever... models are released when the injection process is run against working dbs, especially for mainstream one like neo4j, though a background on Java is required because they are Java oriented.

The doc provided in `PJBS/doc/index.html` is very light and very old but it's sufficient for anyone with some Java knowledge to make it work.

To run PJBS against h2:

1. Run h2,
2. Download h2 jdbc driver and add it the path,
3. Add driver name "org.h2.Driver" to pjbs.conf and to the collection `String[] drivers` in Server.java,
4. Run Server.java,
5. Change the connection in the PHP file to `$drv->connect('jdbc:h2:tcp://127.0.0.1/~/test', 'sa', '');`

Just that the developers of non-mainstream H2 and PJBS are not different species than other open-source developers, and releasing tools that all users can't get to use is not the developers' problem in the first place.

**Comment by stamparm** [comment]
By the way @ron190. You haven't answered my question in the first place. Does any of your (like created by yourself) scripts referenced work?

**Comment by stamparm** [comment]
p.s. @ron190 at the end, I've managed to make it run based on your steps (although, even with steps it requires lots of voodoo to make it work). Hence, thank you for the provided steps - not including the patronizing and scolding part which was out the blue - Ron, I am a human being too ;(

**Comment by stamparm** [comment]
Implementation of H2 support is done

**Comment by huitc** [comment]
ron190 O_O OMG!!!!!!?
