### ISSUE TITLE
Modify Tamper Script

### ISSUE THREAD

**Issue by Chokrii** [sqlmapproject/sqlmap#3365]
Hello Team,
please can any one help me, i managed to bypass a cloud-flare firewall manually ! so i need sqlmap to modify my payload in my case i want to change `schema_name` to be `schema/**/_name` and `Database()` to be `Data/**/base()`
actually is similar to informationschemacomment.py I've tried to modify it but no success (as i'm newbie with python)

Many Thanks

**Comment by huitc** [comment]
+1??😑

**Comment by Chokrii** [comment]
???

**Comment by stamparm** [comment]
```
#!/usr/bin/env python

import re

from lib.core.enums import PRIORITY

__priority__ = PRIORITY.NORMAL

def tamper(payload, **kwargs):
    retVal = payload

    if payload:
        for word in ("Database", "schema_name"):
            retVal = retVal.replace(word, "%s/**/%s" % (word[:len(word) / 2], word[len(word) / 2:]))

    return retVal
```

Note: instead of `for word in ("Database", "schema_name"):` use any list of strings/words where you want that same `/**/` to be inserted into

p.s. I doubt that you've been able to bypass anything with this as inherently those inline comments `/**/` are being replaced by whitespaces inside the DBMS itself. Though, I won't judge nor disregard the fact that there could be some intermediary mechanism that filters it out before the payload comes to the DBMS

**Comment by Chokrii** [comment]
Thanks Stamparm,
not sure too but i was able to get banner ill try now to get the databases many thanks for your support

**Comment by huitc** [comment]
how to bypass `make_set()` <-- by using this tamper script?
like this --> `MAKE_SET(1,'a','b','c')` @stamparm

**Comment by huitc** [comment]
`for word in ("MAKE_SET"):` <--??
cant =.= t.t

**Comment by stamparm** [comment]
A) WRONG: `for word in ("MAKE_SET")`  <- result is an iterator over all characters inside given string
B) CORRECT: `for word in ("MAKE_SET",)`  <- result is an iterator with a single word `MAKE_SET`
