### ISSUE TITLE
Tables "sqlmapoutput" in dbs

### ISSUE THREAD

**Issue by ApTemkA73** [sqlmapproject/sqlmap#3367]
Found that the database has a new table " sqlmapoutput"
1) what does this mean?
2) Do I have the right to add/edit the database?
![screenshot_25](https://user-images.githubusercontent.com/37661593/48434968-a7ba9880-e794-11e8-80e6-05e2456addcc.png)

**Comment by stamparm** [comment]
You've most probably run some of OS access switches/options, where the automatic cleanup failed (e.g. because of `Ctrl-C` or some other problem). Try to rerun with `--cleanup` (find more information [here](https://github.com/sqlmapproject/sqlmap/wiki/Usage#cleanup-the-dbms-from-sqlmap-specific-udfs-and-tables))

**Comment by lldk-rr** [comment]
i want to know when the table " sqlmapoutput" created，
I'm confused，At what stage will it appear

**Comment by stamparm** [comment]
@lldk-rr usually when running any [takeover](https://github.com/sqlmapproject/sqlmap/wiki/Usage#operating-system-takeover) functionality
