### ISSUE TITLE
SQLmapV1.3.1.83When you encounter WAF bypass, you lose your response

### ISSUE THREAD

**Issue by m1m1cat** [sqlmapproject/sqlmap#3464]
My system: Windows 7 X86
SQL map based on pentest box

When SQL map encounters this problem, it loses its response：
do you want SQLmap to try to waf detect backend WAF/IPS？ [y/n]
Whether you choose Y or N
CTRL + C can not be used normally.

**Comment by hos903** [comment]
--batch ;)

**Comment by stamparm** [comment]
@m1m1cat I am really not able to understand what seems to be the problem here. Hence, you have a standard Issue template, which you skipped obviously, which could help in decoding this kind of problems.

![aaa](https://user-images.githubusercontent.com/921555/52216026-a41b4700-2895-11e9-98ae-a81d4fdb80a3.png)
