### ISSUE TITLE
What possible problem about  Blind injection(query sleep)

### ISSUE THREAD

**Issue by xiaoyiddos** [sqlmapproject/sqlmap#3516]
## What's the problem (or question)?
I tested a website and found a injectable head(X-Forwarded-For) , When the payload is #X-Forwarded-For:127.0.0.1' AND (SELECT * FROM (select(SLEEP(5)))Mibm) and 'TfYY'='TfYY# , it works.
Also I tested 'sleep(0)' and it works.
it shows that it's possible like 
MYSQL >= 5.0.12 AND time-based blind (query SLEEP)' injectable
.But at last it tested with #X-Forwarded-For:127.0.0.1' AND (SELECT * FROM (select(SLEEP(5-(IF(53=53,0,5)))))Mibm) and 'TfYY'='TfYY# to comfirm. it didn't work. 
I tried to use 'case when' 、'ELT'  or some other function like that to replace IF, but it didn't still work.
Could you pls tell me what possible problems(WAF) it can hava ?

**Comment by xiaoyiddos** [comment]
![image](https://user-images.githubusercontent.com/46039468/53867223-5cbbde00-402e-11e9-934c-d4236ab86e74.png)

![image](https://user-images.githubusercontent.com/46039468/53867254-6b09fa00-402e-11e9-9d71-35369398daf4.png)

It can only work with sleep(5)  sleep(5-0)  or sleep(5-5) . But when I use boolean expression it failed.
I don't think this problem belong to WAF,

**Comment by stamparm** [comment]
I can't help you more than say that you are on a right track. That's the proper way how to assess the potential SQLi vulnerable target (though, in your case, maybe there is no SQLi in the first place - something else could cause this).

Until you are able to run boolean and/or algebraic expressions, there is no SQLi. After you find a way how to run those, you MUST be able to run subqueries inside those expressions (e.g. `(SELECT 1)` instead of 1, or similar). In the end, if you are able to jump through all those hoops, the amount of time involved is a decisive measure if you'll be able to automate this all in the first place (because something in between could interfere with this whole process). If you've spent more than half an hour, with suspicious looking payload that appears to be working, be sure that automation won't help you (i.e. sqlmap) - though, manual scripting might help

**Comment by stamparm** [comment]
Can't tell. Please follow those steps above. If you are not able to execute any SQL expression as a subquery, then you don't have a (usable) SQL injection case
