### ISSUE TITLE
Connection timed out to the target URL. unable to connect to the target URL[

### ISSUE THREAD

**Issue by sandman4812av** [sqlmapproject/sqlmap#3673]
When web server often downs from many requests, what mechanism you advice for sqlmap using ?
I used --time-sec=15, but no result
Thanks

sqlmap response
[QUOTE]Connection timed out to the target URL.
unable to connect to the target URL[/QUOTE]

P.S there is no WAF/IPS/IDS

**Comment by stamparm** [comment]
1) `--proxy-file` to try from different IPs (if this works, I would be pretty sure that there is WAF/IPS in between)
2) If timeout is caused by `time-based` and/or `stacked-based` SQLi I would try to drop it from `--technique` (e.g. `--technique=BEU`)
3) I would use `--random-agent` just in case
4) Try to rerun everything with `--disable-precon` (as some web servers don't like `pre-connection` mechanism used by sqlmap)
5) Try to use single-threading if multi-threading has been used (e.g. `--threads=1`)
6) Try to force some other technique than the one used by default (e.g. if `UNION` is used, while `ERROR` is available, I would try to force `--technique=E`)

---

Please don't reply to this all with "I already use this or that" as: A) you haven't filled the "Bug report" by a given template and B) I can't make guess games here

**Comment by sandman4812av** [comment]
Thanks for reply

result is https://pasteboard.co/IeWRofBn.jpg

**Comment by huitc** [comment]
--drop-set-cookie
--delay 5

try --null-connection --chunk ?
more --tamper ?

**Comment by huitc** [comment]
can you let me see what inside 33ac.txt ( hide the keyword if you like to

**Comment by SalimF** [comment]
> 4\. `--disable-precon`

That solved my issue with error message `unable to connect to the target url.`,
I was testing it on my localhost PHP web app runs using nginx,
