### ISSUE TITLE
dangerous sql inject test on update statement before where

### ISSUE THREAD

**Issue by niubl** [sqlmapproject/sqlmap#3688]
**Describe the bug**
if there is a sql query like this:
`update users set age=1 where id=1`
and the age is the parameter from outside like this:
`http://example.com/update_before_where.php?age=1`
then, even if simple test payload `and 1=1#` will update all user data
this is very dangerous

**To Reproduce**
1. Run 'python sqlmap.py -u "http://example.com/update_before_where.php?age=1" --risk 1'
2. See the use date in the database

**Expected behavior**
ALL user data will be updated in risk 1 level.

**Screenshots**
![image](https://user-images.githubusercontent.com/4416142/58073359-ecf0d480-7bd4-11e9-84d1-846cec127db1.png)
![image](https://user-images.githubusercontent.com/4416142/58073469-35a88d80-7bd5-11e9-950a-5f061aa6abe7.png)

**Running environment:**
 - sqlmap version [1.3.5.120#dev]
 - Installation method [git]
 - Operating system: [linux]
 - Python version [2.7.5]

**Target details:**
 - DBMS [MySQL]
 - SQLi techniques found by sqlmap [time-based and boolean-based blind]
 - WAF/IPS [no]
 - Relevant console output [no]
 - Exception traceback [no]

**Additional context**
to solve this problen, i suggest add limit 1 before sql comment like this:
``and 1=1 limit 1#``

**Comment by stamparm** [comment]
This is "acceptable risk" from sqlmap's point of view. I won't change the logic just for this single case, which can be (IMO) found in trivial number of cases overall. `--risk=3` includes potentially far more dangerous `OR` payloads. Adding "dumb" `LIMIT` to the end of payload will cut-off support for number of DBMSes just because of syntax limitations/differences.

Hence, I would advise:

1) Either to stop using sqlmap and try to do everything manually
2) Or adjust payloads (just for you - inside `payloads` directory) to have that `LIMIT 1`
3) Or (e.g.) use `--suffix=" LIMIT 1"` whenever possible

p.s. As a matter of fact, you can set an environment variable SQLMAP_SUFFIX=" LIMIT 1" and it will always FORCE usage of that same suffix

**Comment by stamparm** [comment]
One more thing. I just realized that this "bug report" it completely invalid. You've used case `update users set age=1 where id=1 AND 1=1` which doesn't do anything different than usual. Hence, marking this as invalid
