### ISSUE TITLE
cx_Oracle.DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help

### ISSUE THREAD

**Issue by anujanshu** [sqlmapproject/sqlmap#3726]
I have written one python script to connect to oracle database using cx_Oracle.6.1.
While running the script as stand alone with root logged in user,  its is working fine. When I am using the same code in CGI script to connect to oracle database as apache:apache user its failing . and complainging that  " 64-bit Oracle Client library cannot be loaded: "libclntsh.so: cannot open shared object file."

**Comment by stamparm** [comment]
This whole issue doesn't have anything to do with the sqlmap.

You should go to that same link (https://oracle.github.io/odpi/doc/installation.html#linux) and follow the instructions for Linux. You have to download that zip file (32-bit or 64-bit, depending on architecture) and extract those so files to appropriate places.

**Comment by tgatev** [comment]
I'm sorry but your instructions does not works, otherwise we will not ask this question. 

[TERMINAL] $ node test-connect-oracle.js 
Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "libnsl.so.1: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have 64-bit Oracle client libraries in LD_LIBRARY_PATH, or configured with ldconfig.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from 
http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html

[TERMINAL ]$ echo $LD_LIBRARY_PATH 
/usr/lib/oracle/19.6/client64/lib:

**Comment by vanelo** [comment]
Any news here? I have the same problem

**Comment by stamparm** [comment]
Tried to setup the Oracle environment (from scratch - haven't had it installed on current machine) with all the provided information from above and **haven't had any problems**. If the information described [here](https://oracle.github.io/odpi/doc/installation.html#linux) is too complicated, then I would suggest you to skip the `sqlmap/cx_Oracle` stuff altogether.

My machine is Ubuntu 20.04 (clean install instructions):

```
sudo su
mkdir -p /opt/oracle
cd /opt/oracle
wget https://download.oracle.com/otn_software/linux/instantclient/19800/instantclient-basic-linux.x64-19.8.0.0.0dbru.zip
unzip instantclient-basic-linux.x64-19.8.0.0.0dbru.zip
apt install libaio1
echo /opt/oracle/instantclient_19_8 > /etc/ld.so.conf.d/oracle-instantclient.conf
ldconfig
pip install cx_Oracle
exit
```

Results:

![1](https://user-images.githubusercontent.com/921555/95068908-3f695d00-0706-11eb-98c6-4d129e48e1a6.png)

**Comment by vanelo** [comment]
I solved by setting the **ORACLE_HOME** and **LD_LIBRARY_PATH** environment variables. 
Try this
`export LD_LIBRARY_PATH = $ORACLE_HOME /lib`

**Comment by vanelo** [comment]
Sorry, I already solved by setting my **ORACLE_HOME** and **LD_LIBRARY_PATH** environment variables
