### ISSUE TITLE
Missing tamper nonrecursivereplacement !

### ISSUE THREAD

**Issue by fanatos123** [sqlmapproject/sqlmap#3735]
Missing tamper nonrecursivereplacement !

**Comment by stamparm** [comment]
`nonrecursivereplacement` is removed for some time because it was junk. I'll gladly close this issue as invalid (because of junk user content), but before I do:

1) Download https://raw.githubusercontent.com/sqlmapproject/sqlmap/55272f7a3b5a771b0630b7c8c4a61bab7ba8f27f/tamper/nonrecursivereplacement.py and put it to e.g. `/tmp/nonrecursivereplacement.py`
2) Call sqlmap with `...--tamper=/tmp/nonrecursivereplacement.py`
