### ISSUE TITLE
Where is the output-folder on Windows 10 ?!

### ISSUE THREAD

**Issue by SecurityFlaw** [sqlmapproject/sqlmap#3754]
I installed sqlmap correctly on Windows 10.
I dumped some data, and now i can't find the output folder.
What is the standard path for Windows 10?

**Comment by SecurityFlaw** [comment]
Issue can be closed!
Found it on: C:\Users\$USER\AppData\Local\sqlmap\output\

**Comment by stamparm** [comment]
I like self-resolving issues :)

**Comment by thezakman** [comment]
I can't access the AppData\Local\sqlmap\ any idea?

**Comment by stamparm** [comment]
@thezakman you should copy-paste the complete directory name. `AppData` is just a subdirectory inside your `Users` directory

**Comment by dbdonb** [comment]
Guys, is there  a way to configure a custom output folder location?

**Comment by pjajd** [comment]
Where is it in termux..

Plz reply

**Comment by stamparm** [comment]
@noliya can you copy-paste or screenshot the whole message?

**Comment by NicolasKojima** [comment]
[15:24:25] [INFO] fetched data logged to text files under 'C:\Users\小嶋ニコラス\AppData\Local\sqlmap\output\redtiger.labs.overthewire.org'

[*] ending @ 15:24:25 /2023-12-12/

PS C:\sqlmap> cd C:\Users\'myname'\AppData\Local\sqlmap\output
cd : Cannot find path 'C:\Users\'myname'\AppData\Local\sqlmap\output' because it does not exist.
At line:1 char:1
+ cd C:\Users\'myname'\AppData\Local\sqlmap\output
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\'myname'..l\sqlmap\output:String)
[Set-Locati    on], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

the fk??
