### ISSUE TITLE
about --repair

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3809]
```
fetching number of tables LIKE 'backup' in database 'ࠁard'
```
can't fix `ࠁ` this kind of character

**Comment by stamparm** [comment]
A) Again, I don't have enough data.
B) `--repair` is only meant for "fixing" entries which were obvious errors (i.e. entries containing `?`) - usually in blind SQLi cases (boolean, timed, stacked)
C) As far as I know, you could also be the problem as this database looks to me like provided via `-D`. This kind of "erroneous" situations are not meant to be fixed with `--repair`. Those situations are more user-terminal related
