### ISSUE TITLE
reflective value(s) found and filtering out

### ISSUE THREAD

**Issue by Illuminati00** [sqlmapproject/sqlmap#384]
What means that?
Can i prevent this with any command?
--hex dont change thar error.

Screenshot: http://archiv.so/images/2013/02/04/cPWrs.png

**Comment by pan-long** [comment]
Hi I saw the same warning. Can you please point me to more details about why "reflective" values are bad?

**Comment by stamparm** [comment]
Imagine a page which is static, except with small part where it echoes/reflects the tested parameter value (same one where the sqlmap performs injection). In case that such "reflective" content is not detected and neutralized there is a considerable chance that it will appear as changing due to used SQLi payloads (e.g. AND 2>3). Hence, risk of false-positive (or false-negative in some cases) detection arises.

So, to sharpen the detection capabilities such reflective "junk" is removed.

p.s. Trivia: lots of detection engines are really bad at detection in such cases, except sqlmap

**Comment by pan-long** [comment]
@stamparm I see, thanks for the clear explanation!
