### ISSUE TITLE
sql shell via web backdoor

### ISSUE THREAD

**Issue by kobyan** [sqlmapproject/sqlmap#4286]
Sometimes we have the option to upload files to the target server (via LIMIT 'LINES TERMINATED BY' method or UNION method). So we can add our file to execute our sql commands on the server. Thus, we can execute CREATE / UPDATA / DELETE commands without Stacked queries injection and get the full output of SELECT queries without Union query-based injection. Credentials for connecting to the database can be obtained from the source files existing on the server.

**Comment by stamparm** [comment]
This "feature" would be unusable by regular users. sqlmap requires a strict "interface" inside the uploaded files so it could communicate with it. Also, if you requested that sqlmap uploads something for you, this is also out of question as there is no way for sqlmap to test whether it "worked" or not because of lack of the predefined "interface"

**Comment by kq12-dev** [comment]
> Sometimes we have the option to upload files to the target server (via LIMIT 'LINES TERMINATED BY' method or UNION method). So we can add our file to execute our sql commands on the server. Thus, we can execute CREATE / UPDATA / DELETE commands without Stacked queries injection and get the full output of SELECT queries without Union query-based injection. Credentials for connecting to the database can be obtained from the source files existing on the server.

<script>alert(document.cookie)<script>
