### ISSUE TITLE
not working with url

### ISSUE THREAD

**Issue by saikiran994** [sqlmapproject/sqlmap#4309]
i tried to do test with one URL to check vulnerabilities,  its showing error. i tried in windows with cmd.
![Screenshot (217)](https://user-images.githubusercontent.com/37449869/90322079-7ffdf300-df6d-11ea-867b-b7d9e83b55f5.png)
![Screenshot (218)](https://user-images.githubusercontent.com/37449869/90322080-81c7b680-df6d-11ea-8cbf-098dda026591.png)

**Comment by geoguit** [comment]
The server only accepts connections with a valid User-Agent header. Use the `--random-agent` parameter when testing and it should work.

P.S I'm not sure if this is intentional or not, but you haven't specified any parameters for sqlmap to test for vulnerabilities, so even when you get the connection working, sqlmap still won't be able to help you, it's not magic!

**Comment by stamparm** [comment]
you can't post real sites here
