### ISSUE TITLE
garbled text in oracle

### ISSUE THREAD

**Issue by 13Em0SPVPaoq** [sqlmapproject/sqlmap#4356]
i tried `--encoding BIG5` `--encoding BIG-5`...
```
back-end DBMS: Oracle
SELECT parameter, value FROM v$nls_parameters WHERE parameter LIKE '%CHARACTERSET' [2]:
[*] NLS_CHARACTERSET, ZHT16MSWIN950
[*] NLS_NCHAR_CHARACTERSET, AL16UTF16

back-end DBMS: active fingerprint: Oracle 10g
               banner parsing fingerprint: Oracle 10.2.0.5.0
banner: 'Oracle Database 10g Enterprise Edition Release 10.2.0.5.0 - 64bi'
```

**Comment by stamparm** [comment]
In some situations there is a possibility that you won't get valid data in any way because of losing data due to incompatible encoding between |backend|<->|database connector|<->|frontend|. This is a known non-sqlmap issue. You could also try to do the `--binary-fields` or force some slower technique (e.g. if you have UNION and boolean-based blind, you can try to force the `--technique=B`) <- I am playing guessing here AGAIN as people just don't care about proper template filling

**Comment by stamparm** [comment]
putting this as invalid because of the lazy user syndrome
