### ISSUE TITLE
All tested parameters do not appear to be injectable. Try to increase values for '--level'/'--risk' options if you wish to perform more tests.

### ISSUE THREAD

**Issue by hack3rcon** [sqlmapproject/sqlmap#4364]
Hello,
I downloaded "Hack the LAMPSecurity: CTF4 (CTF Challenge)" and wants to use SqlMap for a SQL Injection attack. According to [https://www.hackingarticles.in/ctf-challenges-walkthrough/](url) website, the author used below command and found an injection attack:
`sqlmap -u http://192.168.1.103/index.html?page=blog&title=Blog&id=2 --dbs --dump --batch`
But I can't :(
I did above and below command too:
`$ sudo sqlmap -u 'http://192.168.56.5/index.html?page=blog&title=Blog$id=5' --dbs --random-agent --tamper=space2comment --level 3 --risk 3 --dump --batch`
But SqlMap tell me:

> 15:15:57] [WARNING] parameter 'Referer' does not seem to be injectable
[15:15:57] [CRITICAL] all tested parameters do not appear to be injectable. Try to increase values for '--level'/'--risk' options if you wish to perform more tests

What is my problem? Is it a bug?

Thank you.

**Comment by hfz1337** [comment]
Hi,

This has nothing to do with `sqlmap`, the reason it's not working for you is the following:
### In the first payload:
- Your URL should be quoted so that the shell doesn't interpret `&` as a special character (run the process in background)
- The command should be: `sqlmap -u 'http://192.168.1.103/index.html?page=blog&title=Blog&id=2' --dbs --dump --batch` instead, you can also specify the parameter that you think is injectable using the `-p` switch, so `-p id` in this case would tell `sqlmap` to only test the `id` parameter.
### In the second payload:
- You made a typo, `$id=5` instead of `&id=5`

Also, I highly recommend that you try to do the SQL injection manually too, this will help you better understand how automated tools work under the hood.

Cheers!

**Comment by stamparm** [comment]
Sorry, you'll have to find it on your own. I am out of time for downloading random machines which should apparently work in case of sqlmap.

Please rerun your case with `--parse-errors` and `-t traffic.txt`. Especially check the traffic file (i.e. `traffic.txt`) for any signs of error. Also, you are using `--tamper=space2comment` for no apparent reason, while I can't find that the author of that blog post mentioned it.

**Comment by bugbounty101** [comment]
my sqlmap not even showing vulnerable web applications like dvwa, multidae as vulnerable . Why this is happening 
`"http://192.168.1.15/mutillidae/index.php?page=user-info.php&username=admin&password=hello123&user-info-php-submit-button=View+Account+Details"`
Please help me to solve this issue

**Comment by LJHunkovic** [comment]
I ran into the identical issue.  I kid you not, instead of writing the URL by hand, I went back, copied, then pasted it into the Terminal and then it worked.  Perhaps the dashes in the URL are long, versus short.  

Anyway, give this a try and I hope that it helps.

**Comment by Jacob-z691** [comment]
zz

**Comment by LuizSim** [comment]
[20:39:13] [WARNING] HTTP error codes detected during run:
403 (Forbidden) - 86 times

**Comment by Jacob-z691** [comment]
> [20:39:13] [警告] 运行期间检测到的 HTTP 错误代码： 403（禁止访问） - 86 次
Check whether your permissions allow it. Does the site you want to test require login?
