### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by FireFart** [sqlmapproject/sqlmap#44]
the newly added switches/options are not documented in the manual.
Examples: --hex, --host, --force-ssl, --titles, --check-tor, ....

But they are visible using the -h option so its no big deal ;)

This is related to issue #46.

**Comment by AbdooRaf3** [comment]
pleas help me with this problem
root@kali:/usr/share/sqlmap# sqlmap -update
         _
 ___ ___| |_____ ___ ___  {1.0-dev-nongit-20151206}
|_ -| . | |     | .'| . |
|___|_  |_|_|_|_|__,|  _|
      |_|           |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting at 10:13:23

[10:13:25] [CRITICAL] host 'pdate' does not exist

[*] shutting down at 10:13:25

root@kali:/usr/share/sqlmap#

**Comment by stamparm** [comment]
@AbdooRaf3 you've mistyped `--update`. So, instead of:

`sqlmap -update`

try to use:

`sqlmap --update`

**Comment by stamparm** [comment]
Done
