### ISSUE TITLE
c-treeACE DBMS Support

### ISSUE THREAD

**Issue by MarkRyancom** [sqlmapproject/sqlmap#4415]
Hello,
is there any plans to add [ c-treeACE Database ] support to SQLMAP anytime soon?

**Comment by stamparm** [comment]
Sorry but no:

![1](https://user-images.githubusercontent.com/921555/98169549-c3bd2480-1eec-11eb-9aa1-4ec95c7edcd5.png)

Setting up the "vulnerable" environment is the greatest obstacle, where it is not an easy task to do, especially in this kind of non-mainstream cases with obscure DBMSes. If you are willing to provide, I could probably do it (as I can see it provides the RDBMS/SQL functionality, so it could be a candidate). Otherwise, nothing
