### ISSUE TITLE
--no-logging option

### ISSUE THREAD

**Issue by kobyan1** [sqlmapproject/sqlmap#4484]
Sometimes logs grow over several GBs. Today I found an 11 GB sqlmap log. Therefore, it would be great if there was an option that would turn off the saving of logs. Something like --no-logging

**Comment by stamparm** [comment]
I am confused because of couple of things:

1) you are the first in >10 years that have this kind of request
2) so, your `log` files are 11 GB. Are you sure? Maybe session files or something, but log files?!
3) if you have 11 GB of log files and you want to disable saving of them, I am not sure how do you even handle such HUGE amount of data

anyhow, i need strong confirm that your `log` file(s) grow 11 GB (not other files). If one line of log (even in table dump) is on average 100 bytes in size, 11 GB would mean `11 * 1024 * 1024 * 1024 / 100` == 118 million lines AND I seriously doubt that

**Comment by stamparm** [comment]
sorry for being such jackass, but because of that last calculation of 118 million lines of log file, I am seconds away from closing this down as invalid

**Comment by andreascreten** [comment]
I have the same issue, dumping a table with 300k items.

**Comment by kernelzeroday** [comment]
> sorry for being such jackass, but because of that last calculation of 118 million lines of log file, I am seconds away from closing this down as invalid

thank you for coming back and fixing this, this has happened to me for years and i never thought to make a bug of it. heres some definite proof that it existed if you were still in doubt:


```txt
$ du -hs *
1.5G	dump
 18G	log
832M	session.sqlite
4.0K	target.txt
```

**Comment by kernelzeroday** [comment]
also if it helps, i made my font very very very very small and cat'd the file and it was mostly whitespace, like super long lines of whitespace for miles

**Comment by kernelzeroday** [comment]
Again sorry for commenting a third time on a closed issue, the reason I never reported this as a bug was because i believed the log was critical for sqlmap to operate, which it appears it is not, and that perhaps it was so large due to containing BASE64 output of binary contents, which can inflate size, so I basically assumed this was the expected behavior and would just go find a box with a very large hdd for my SQL vuln testing automations. I think a lot of people probably felt the same way. 

Was there another thread that caused this to be reopened and fixed? Sorry, just curious waking up this morning about the tale of the ever expanding log file, I've been confused by this for literally 10 years without giving it any deeper thought. Perhaps SQLMAP is logging the max field length as whitespace? Whatever bug causes this is still present, even thought now we can stop writing to log, I would like to be able to write an accurate log without it being 18gb.

**Comment by stamparm** [comment]
@kernelzeroday i would really need some example to be able to address it properly
