### ISSUE TITLE
Need help about handling URL

### ISSUE THREAD

**Issue by yl12053** [sqlmapproject/sqlmap#4585]
Sorry, but i need some kind of help.
When the statement is true, it will jump to url1
When the statement is false, it will jump to url2
How can I handle this kind of situation with sqlmap?
Sorry for my poor English.

I have tried second-order, but it always return ```[CRITICAL] unable to connect to the target URL``` when the statement is true.

**Comment by stamparm** [comment]
1) this should be straightforward for handling by sqlmap. Please use `-v 6` or `-t traffic.txt` to find out what is going on
2) that `[CRITICAL] unable to connect to the target URL` doesn't look like a problem is in sqlmap (either WAF or some poor redirection is going on)
3) you can try to use basic stuff like `--random-agent` or similar because the target could be doing some trivial bot prevention
