### ISSUE TITLE
New payload with "SIMILAR TO"

### ISSUE THREAD

**Issue by kobyan1** [sqlmapproject/sqlmap#4786]
Please add a new payload using the "SIMILAR TO" statement for postgresql and also using '~'.
Analogies with existing payloads using "like":
'[RANDSTR]' LIKE '[RANDSTR]' => '[RANDSTR]' SIMILAR TO '[RANDSTR]' => '[RANDSTR]' ~ '[RANDSTR]'
Documentation - https://www.postgresql.org/docs/current/functions-matching.html

**Comment by stamparm** [comment]
1) That part which you are referring to are just boundaries (not the actual payload), thus, they are not too useful
2) I tried to actually use that `SIMILAR TO` inside the payloads, but they are not too flexible. In all major DBMS-es, we are converting pieces of strings to their ASCII code values, then do an inference (those `>` payloads) to extract the content. `SIMILAR TO` is unfortunately not useful here because it strictly works with strings
3) Same ^^ applies for `~`
