### ISSUE TITLE
injectable with --string

### ISSUE THREAD

**Issue by mxmsec** [sqlmapproject/sqlmap#4838]
Hello i have issue,, and try to slove it with string but cant..

[18:56:14] [INFO] (custom) POST parameter 'SOAP #1*' appears to be 'AND boolean-based blind - WHERE or HAVING clause (subquery - comment)' injectable (with --string="405 000000000000000000000000400000000000000     00"

i have "Blind SQL Injection" injectable ... but with string 
and i cant try again without used --flush-session cuz i have save info req.

** and, some time i have this msg 
injection not exploitable with NULL values. Do you want to try with a random integer value for option '--union-char'? [Y/n]
if you can explain to me --union-char=(?) about union-char

please if you can help ?
Thank You.

**Comment by stamparm** [comment]
1) sorry, but i couldn't understand the problem with `--string`. what's the issue here: `i have "Blind SQL Injection" injectable ... but with string`???
2) `--union-char` can be modified by user to some arbitrary value for usage during the UNION SQLi testing. As UNION SQLi has to cover all columns used in original (vulnerable) query, and as in some cases original `NULL,NULL,NULL....` approach doesn't work, sqlmap asks whether you want it to use some random integer value for that `--union-char` (e.g. `3312,3312,3312,3312,...`)

**Comment by mxmsec** [comment]
> 
> 
>     1. sorry, but i couldn't understand the problem with `--string`. what's the issue here: `i have "Blind SQL Injection" injectable ... but with string`???
> 
>     2. `--union-char` can be modified by user to some arbitrary value for usage during the UNION SQLi testing. As UNION SQLi has to cover all columns used in original (vulnerable) query, and as in some cases original `NULL,NULL,NULL....` approach doesn't work, sqlmap asks whether you want it to use some random integer value for that `--union-char` (e.g. `3312,3312,3312,3312,...`)


I HAVE THIS MSG ON SQLMAP:

[18:56:14] [INFO] (custom) POST parameter 'SOAP #1*' appears to be 'AND boolean-based blind - WHERE or HAVING clause (subquery - comment)' injectable (with --string="405 000000000000000000000000400000000000000 00"
