### ISSUE TITLE
Specifying arbitrary injection points

### ISSUE THREAD

**Issue by mwulftange** [sqlmapproject/sqlmap#484]
It would be great if SQLMap would support arbitrary injection points denoted by some special marker, not only in the URL but also in the request.

**Comment by olekukonko** [comment]
The documentation on this functionality needs to be improved ...

**Comment by stamparm** [comment]
@olekukonko https://github.com/sqlmapproject/sqlmap/wiki/Usage#arbitrary-injection-point

better?

**Comment by olekukonko** [comment]
Yes much more better ... We also improve it better because most people would likely look for `%Inject_Here%` instead of properly reading the documentation.

**Improved Introduction** 

Similar to URI injection point, such as `${InjectHere}` and `%Inject_Here%` which is not supported in  `sqlmap` , asterisk (*) can also be used to point to the arbitrary ........... 

What do you think ?

**Comment by stamparm** [comment]
`%Inject_Here% which is not supported in sqlmap` <- actually, it is supported. Documentation updated

**Comment by olekukonko** [comment]
Lol .. This makes more sense now ... nice one
