### ISSUE TITLE
Interactsh Intergration

### ISSUE THREAD

**Issue by unionor** [sqlmapproject/sqlmap#4903]
Integrating Interactsh will make dns exfiltration easier.

https://github.com/projectdiscovery/interactsh

**Comment by MissisEliot** [comment]
It would be cool if stamp embedded this tool in sqlmap and it worked with all types of dbs

**Comment by stamparm** [comment]
1) sqlmap dates WAY before burp collaborator or similar, when it was a blasphemy to use any kind of "exfiltration" utilities. Havij has been demonized because of doing this, while Burp is kind of ok to do it by default
2) how can user use `Interactsh` in simple and "anonymous" way, which is easier than the current requirements for dns exfiltration?

**Comment by MissisEliot** [comment]
> 1. sqlmap dates WAY before burp collaborator or similar, when it was a blasphemy to use any kind of "exfiltration" utilities. Havij has been demonized because of doing this, while Burp is kind of ok to do it by default
> 2. how can user use `Interactsh` in simple and "anonymous" way, which is easier than the current requirements for dns exfiltration?


Maybe you are integrating?
and choose between sqmap dns and Interactsh?
so that the user has a choice and everything starts out of the "box"

**Comment by stamparm** [comment]
revisited:

* although a good idea, self-hosting of interactsh requires controlling of the domain (just another layer around the requirements for sqlmap dns exfiltration)
* i am not a huge fan of sending anything from sqlmap to any third-party. period
