### ISSUE TITLE
"flush-session" vs "fresh-queries" differencies 

### ISSUE THREAD

**Issue by enseitankado** [sqlmapproject/sqlmap#5118]
I could not find any information in the documentation about when these two keys can be used together. Looks like they both do the same job. If I'm wrong, can you give an example of a situation where these two options are used simultaneously? I really don't understand why these two would be used at the same time.

**Comment by stamparm** [comment]
One is doing a permanent delete of the session (`--flush-session`), the other is ignoring the session (`--fresh-queries`). You should not use them together because it doesn't make any sense to do that.

As of "I could not find any information in the documentation", AFAICS, documentation here: https://github.com/sqlmapproject/sqlmap/wiki/Usage#ignore-query-results-stored-in-session-file is more than clear enough:

```
Switch: --fresh-queries

As you are already familiar with the concept of a session file from the description above, it is good to know that you can ignore the query results by using option --fresh-queries. This way you can keep the session file untouched and for a selected run, avoid the resuming/restoring of queries output.
```
