### ISSUE TITLE
MariaDB WAF bypass and sql injection

### ISSUE THREAD

**Issue by procrash8247** [sqlmapproject/sqlmap#5149]
I have a site having issues , just dont know how to inject it , even if trying there is WAF which is constantly blocking my request
Named : Imunify360 (cloudLinux)
How to bypass it ?

here is the MariaDB error which i get.
Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'IS NULL' at line 3

SELECT * FROM `bride_groom_details` WHERE IS NULL

Filename: controllers/Common.php

Line Number: 42

**Comment by CostyCrypto** [comment]
try with

--random-agent --flush-session --tor --drop-set-cookie --tamper=[tamperscript] --level=3 --risk=3
--random-agent --flush-session --proxy-freq=3 --proxy-file=proxylist.txt --drop-set-cookie --tamper=[tamperscript] --level=3 --risk=3

if u have problem with connection timeout because of the ip banning don't use --batch

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/FAQ#which-tamper-script-to-use-to-bypass-a-wafips-protection
