### ISSUE TITLE
Is there any way to fetch the data with just 1 request?

### ISSUE THREAD

**Issue by decuple-dream** [sqlmapproject/sqlmap#5246]
Dear @stamparm , how are you? 

When the vulnerability and all options (-D, -T, -C) are specified, I want to import data with only one request. 

For example, the current --dump option and --skip-waf, --skip-static, --skip-heuristics are used together, and when extracting data, check the connection of the target, run a query two or three times and start union base extract queries.(Actual Data Extraction Query)

Is there any other option to pull the data in one request without even checking the target internet connection? (hidden --skip option?)  and I want to ignore it and run the query again when the connection is reset. (Sorry for the many requests.)

Thank you for always. Cheers for you!

**Comment by stamparm** [comment]
* To skip something during the tests, use `--skip-heuristics --skip-waf` (as you already noticed)
* During the data retrieval, sqlmap has to do at least the "testing connection to the target URL". It is important part of the workflow, not just because it "tests the connection", but sqlmap also retrieves the characteristics of the web content and response inside of that same "test", so it could properly differentiate "original" from non-original responses
