### ISSUE TITLE
who can help me?

### ISSUE THREAD

**Issue by vFREE-1** [sqlmapproject/sqlmap#5264]
are you really sure that you want to continue (sqlmap could have problems)? [y/N]

**Comment by stamparm** [comment]
I would advise you to press `N`

p.s. you forgot to paste the whole message starting with `it appears that you have provided tainted parameter values`. If you haven't done anything silly with the parameter values (e.g. copy-pasting from Acunetix or Burp or some manual SQLi attempts) then you can try to press `y`. Otherwise, `N` and close the terminal
