### ISSUE TITLE
How to support comparison FASLE code ?

### ISSUE THREAD

**Issue by sg552** [sqlmapproject/sqlmap#5405]
**Is your feature request related to a problem? Please describe.**

currently sqlmap only support TRUE comparison result, e.g. `--code`, can we support FALSE comparison code? 

e.g. `sqlmap -u ... --not-code=400`

**Comment by stamparm** [comment]
There are already tons of options that you could try to use. If you have a code for "FALSE", then most probably you also have a code for "TRUE" (otherwise, it wouldn't make any sense to even test such case)

Also, you can try to use `--not-string=NOT..  String to match when query is evaluated to False` if you have a solid case with FALSE response
