### ISSUE TITLE
Please, create option --dbms-version

### ISSUE THREAD

**Issue by GiuBravo** [sqlmapproject/sqlmap#5422]
When i alrery know The DBMS and Version, I want to specifie the version to avoid desnecessary requisitions.

**Comment by decuple-dream** [comment]
I'm equally hopeful about this. Currently, SQLMAP is failing to match versions for some reason.
```
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: uid (POST)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: uid=6' AND 3691=3691 AND 'NPrA'='NPrA&idx=notice&gs=24ls1i1blrqdi091ck37pedgh01677745750
    Vector: AND [INFERENCE]

    Type: UNION query
    Title: Generic UNION query (NULL) - 29 columns
    Payload: uid=-4050' UNION ALL SELECT NULL,NULL,NULL,NULL,CONCAT(0x7171716b71,0x5a58476a4f4c6a4b696743674d526d58747a6e4f44536172757557494e516d70754b7a584f485672,0x7171787871),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL-- -&idx=notice&gs=24ls1i1blrqdi091ck37pedgh01677745750
    Vector:  UNION ALL SELECT NULL,NULL,NULL,NULL,[QUERY],NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL-- -
---
[14:57:49] [WARNING] changes made by tampering scripts are not included in shown payload content(s)
web application technology: Nginx
back-end DBMS: MySQL Unknown
[14:57:49] [WARNING] information_schema not available, back-end DBMS is MySQL < 5.0
do you want to use common column existence check? [y/N/q]
```

However, if you use the --sql-query option to search for tables and columns like this, it works fine.

`--sql-query="SELECT column_name FROM information_schema.columns WHERE table_schema='dbname' AND table_name='tbname'`

Unfortunately, if you take the information from this and give it the -D, -T, and -C options, it will still output the same version < 5.0 error and exit.

**Comment by decuple-dream** [comment]
>  instead of you two trying to "force-feed" sqlmap with "i am sure that this is right version of MySQL", maybe you could actually try to debug what's going on. like, run with -v 3 and see where sqlmap fails. force-feeding an automated tool is never a good idea

If SQLMAP has already detected that the target RDBMS is version < 5.0, giving the -v 3 option will not send any payload and will eventually ask if you want to run a common table.

I suspect that SQLMAP initially failed due to some function or keyword when detecting the vulnerability and searching for the version, but in the end the version is 5.0 or higher.

I wish SQLMAP could recognize versions via the -f option.

**Comment by stamparm** [comment]
there are lots of queries being done during the regular fingerprinting (not explicit `-f`) is done:

`QUARTER(NULL XOR NULL) IS NULL`
`ISNULL(JSON_STORAGE_FREE(NULL))`
`ISNULL(TIMESTAMPADD(MINUTE,12345,NULL))`
...

something fails. that's why i told you to debug what's going on (run with `-v 3` and inspect the results)

**Comment by decuple-dream** [comment]
> there are lots of queries being done during the regular fingerprinting (not explicit `-f`):
> 
> `QUARTER(NULL XOR NULL) IS NULL` `ISNULL(JSON_STORAGE_FREE(NULL))` `ISNULL(TIMESTAMPADD(MINUTE,12345,NULL))` ...
> 
> something fails. that's why i told you to debug what's going on (run with `-v 3` and inspect the results)

`(QUARTER(NULL XOR NULL) IS NULL)` is doesn't seem to work.
Is there a different way to check it?

**Comment by stamparm** [comment]
can you try to capture such request via Burp and replay it? then instead of `(QUARTER(NULL XOR NULL) IS NULL)` try `(QUARTER(NULL) IS NULL)` and `(NULL IS NULL)`

**Comment by kobyan** [comment]
> instead of you two trying to "force-feed" sqlmap with "i am sure that this is right version of MySQL", maybe you could actually try to debug what's going on. like, run with `-v 3` and see where sqlmap fails. force-feeding an automated tool is never a good idea

When using sqlmap, there are cases when it tries to determine the full version of the DBMS from VERSION (), and not approximately through fingerprinting.
For example, when doing --os-shell in PostgreSQL via stacked queries.
If stacked queries are the only SQLi type for this request, then getting the DBMS version will be very long and there is a high probability of errors due to connection instability.

In this case, the force-feed feature would be extremely useful.
