### ISSUE TITLE
Wrong log file on Windows

### ISSUE THREAD

**Issue by pak0s** [sqlmapproject/sqlmap#5463]
**To Reproduce**
1. Run SQLMAP on Windows (11 in my case)
2. At the end of dump, SQLMAP will say something like `[15:23:12] [INFO] fetched data logged to text files under 'C:\Users\user\AppData\Local\sqlmap\output\example.com'`
3. There is no SQLMAP directory in `C:\Users\user\AppData\Local\`
4. Instead data is logged in directory `C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_xxxxxxxxx\LocalCache\Local\sqlmap\output`

**Expected behavior**
Fix the message or either fix the path

**Running environment:**
 - sqlmap version [1.7.7#stable]
 - Installation method [simple git clone and running as `python3 sqlmap.py`]
 - Operating system: [Microsoft Windows 11]
 - Python version [3.11.4]

**Target details:**
 - DBMS [Oracle]

**Comment by stamparm** [comment]
![1](https://github.com/sqlmapproject/sqlmap/assets/921555/6e9011f8-bfbf-469b-b946-94917aefc326)

**Comment by thiem-dev** [comment]
I just had this issue too. The problem is that Python installed from the Microsoft store runs in a sandbox environment that redirects the PATHs to `C:\Users\user\AppData\Local\Packages` . 

The fix is to uninstall the Microsoft store python. And install the one from official python `https://www.python.org/downloads/`. Then rerun with: `python sqlmap.py -r "req1.txt" --batch --dump --flush-session` and it should go to the correct paths. 😎
