### ISSUE TITLE
Sqlmap did not detect SQL injection

### ISSUE THREAD

**Issue by Mr-x2020** [sqlmapproject/sqlmap#5494]
With the help of an ACUNETix scanner, I found a SQL injection vulnerability. I tried to dump the database with SQLmap, but I couldn't, but I couldn't. It took me three days to figure out why it wasn't detecting SQLi. I tried all SQLmap tampers and made up tampers, but they also didn't work.
So I decided to try another tool to dump DB called Ghauri and succeeded. In dumping the whole database.
Eventually, I found out that the problem was in sqlmap itself

![image](https://github.com/sqlmapproject/sqlmap/assets/65666323/8fdef39a-d354-4460-99bb-0f22cf0152d8)

**Comment by stamparm** [comment]
you are more than welcome to use those tools if you find them better

**Comment by Mr-x2020** [comment]
> you are more than welcome to use those tools if you find them better

It's just a bug report, not an argument

**Comment by mtisec** [comment]
Hey @Mr-x2020, your issue is hard to parse. You actually provide meaningful data for your issue. As is, it does not provide much insight. What would help:

1. Provide a proper overview of your context. a) What has been reported by Acunetix. b) What are the sqlmap commands you have tried and c) what has been their result / final output? 
2. Have you validated, that sqlmap hits your injection point right? Try setting the verbosity to `-v 4` to see the actual requests or pipe them through Burp, etc.
3. The payload Ghauri is using is found in sqlmap's payloads (as it seems the author of Ghauri mostly copied sqlmap; this is especially nasty, because it does not mention it's "inspiration" / clone source anywhere)
4. Your payload is here: https://github.com/sqlmapproject/sqlmap/blob/79aa3153444d0aa57616de943c54f054ed473fe8/data/xml/payloads/boolean_blind.xml#L849
5. Actually do diff of the requests of both tools and try to figure out, why sqlmap is not sending the one you would have needed.

**Comment by LiamHwang** [comment]
I have the same problem,sqlmap does not detect some existing vulnerabilities. I use the same command and payload but i cant detect the sql vulnerablity in sqli-labs/less18-19/ like the others do. And i dont know how to solve it.
