### ISSUE TITLE
Hello i have a problem when i try to start sqlmap it always says host does not exist

### ISSUE THREAD

**Issue by xTy8** [sqlmapproject/sqlmap#5499]
![IMG_0912](https://github.com/sqlmapproject/sqlmap/assets/78267173/98e63fbc-bd35-4c36-983b-e1a66aab6e90)

**Comment by xTy8** [comment]
sqlmap ** not mysql

**Comment by Qadir-Hassan** [comment]
The error message "host does not exist" in SQLMap typically indicates that the provided target URL or IP address cannot be resolved. This could be due to various reasons:

Incorrect Hostname or URL: Make sure you've entered the correct target URL or IP address. Double-check for typos, missing characters, or incorrect formatting.

Network Connection: Ensure that your machine has an active and stable internet connection. SQLMap needs to connect to the target host to perform its scans.

Target Unreachable: The target host might be down or not reachable from your machine. Make sure the host is up and running.

Firewall or Network Restrictions: Your network or firewall settings might be blocking SQLMap's access to the target host. Check your firewall settings and network configurations.

HTTP/HTTPS Prefix: Ensure you've included the appropriate prefix (http:// or https://) in the target URL.

DNS Resolution: If you're using a domain name, ensure that the DNS resolution for that domain is working correctly.

IP Whitelisting: If the target has IP whitelisting, your IP might not be allowed to access the target.

**Comment by xTy8** [comment]
@Qadir-Hassan what if i try to delete sqlmap and reinstall it would it help?

**Comment by stamparm** [comment]
that same hostname can't be resolved on your machine. try to do `dig tpsldh.com`

also, you've completely skipped the error template. there is zero information on used options and switches

**Comment by kingsley-developer** [comment]
I faced similar issue what should i do
