### ISSUE TITLE
Where did the data dump goes?

### ISSUE THREAD

**Issue by mertyzzz** [sqlmapproject/sqlmap#5503]
Hello, ive been dumping database from this sites for 2 days. Yesterday was still fine, but today i got this message
![test](https://github.com/sqlmapproject/sqlmap/assets/143153299/17471104-48f9-4d84-826d-0e02b8d5714e)
Ok there is a problem with the sites, but where is the data dump goes now? I check the output folder and nothing there

Does the dump failed at all? There is no temporary storage or temporary dump at all?

**Comment by mertyzzz** [comment]
The datas is nowhere to found, i've been checking logs and session.sqlite files and nothing there. The log files and sqlite also under 8 kb which is not recording from the start.

That just great.

**Comment by stamparm** [comment]
sorry to hear that. seems that website started to block you  (see the number of 403 HTTP error codes). also, dropping of SSL/TLS HTTP requests is always a bad sign.

there is no temporary log file as sqlmap requires full table to be able to postprocess its content and display it properly (e.g. in some cases, column values are retrieved one by one instead of rows)

as of missing files, i would expect session sqlite file to be there with at least something inside (even unreadable, as some forms of a dump are stored in a serialized way)
