### ISSUE TITLE
add auto tamper in sqlmap

### ISSUE THREAD

**Issue by seyedhojjathosseini** [sqlmapproject/sqlmap#5558]
I want to inform the SQLMap team that I've written a script that speeds up the testing of tamper scripts for me. It would be better to add this option to SQLMap; it's very useful for us. Thank you. 

Here's the link to my script: https://github.com/seyedhojjathosseini/sqlmap-AutoTamper

**Comment by stamparm** [comment]
well, your script is pretty simple. auto-tampering in such way was never an option. also, dummy running of all tamper scripts in a sequential way most probably would not help you against some random target (i.e. you'll get scanning time increased to hours or days, instead of minutes). will close this down and people can try your script at any time
