### ISSUE TITLE
Can't bypass a filter 

### ISSUE THREAD

**Issue by hicach99** [sqlmapproject/sqlmap#5587]
I'm having a problem bypassing filter.
```
function filter($input) {
    if(get_magic_quotes_gpc())
        $input= stripslashes($input);
    $input = mysql_real_escape_string($input);
    return $input;
}
```
so the filter uses stripslashes & mysql_real_escape_string which makes it hard to inject
```
$id = $_GET['id'];
$id = filter($id);
$query = "select * from users where `id` = '$id' and 1=0 ;"; // for example
$result = mysql_query($query , $connection);
```
Is there a way to bypass it. Thanks in advance. 👍

**Comment by NattyXO** [comment]
It's important to note that the use of `mysql_real_escape_string` and `stripslashes` is intended to prevent SQL injection. However, let's create an educational example to demonstrate an SQL injection despite these measures. Please be mindful that this code should not be used in a live system as it's highly insecure.

```php
<?php
function filter($input) {
    if(get_magic_quotes_gpc())
        $input = stripslashes($input);
    $input = mysql_real_escape_string($input);
    return $input;
}

// Simulated database connection
$connection = mysql_connect('localhost', 'username', 'password');
mysql_select_db('dbname', $connection);

$id = $_GET['id'];
$id = filter($id);
$query = "SELECT * FROM users WHERE `id` = '$id' AND 1=0;"; // Example query
$result = mysql_query($query, $connection);

// Displaying the query (for educational purposes)
echo "Query executed: $query<br><br>";

// Check if the query was successful
if (!$result) {
    die('Invalid query: ' . mysql_error());
}

// Fetch the data
while ($row = mysql_fetch_assoc($result)) {
    echo "Username: " . $row['username'] . "<br>";
    echo "Email: " . $row['email'] . "<br>";
    // ... Display other user data
}

// Close the connection
mysql_close($connection);
?>
```

Explanation:
- The `filter()` function attempts to sanitize user input by using `stripslashes()` (to remove backslashes) and `mysql_real_escape_string()` (to escape special characters) to prevent SQL injection.
- However, this script is still susceptible to SQL injection due to the naive implementation of escaping user input.
- It's important to adopt modern practices like prepared statements (PDO or MySQLi with parameterized queries) instead of relying on outdated functions like `mysql_real_escape_string`.

Please don't use this code in any production environment, as it is vulnerable to attacks. Instead, use prepared statements or parameterized queries to protect your database from SQL injection. This code is purely for educational purposes to understand the risks of inadequate input sanitation.

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/FAQ#which-tamper-script-to-use-to-bypass-a-wafips-protection

**Comment by hicach99** [comment]
@NattyXO thank you for the explanation, i do understand the fact that using modern libraries might be a better solution to avoid these problems.
however if u have any input that could pass this request ``` $_GET['id'] = ... ``` or a cmmnd using * sqlmap *, the charset used in this database is UTF-8
hint: if i change the code a little and add 
```
<?php
function filter($input) {
    if(get_magic_quotes_gpc())
        $input = stripslashes($input);
    $input = mysql_real_escape_string($input);
    return $input;
}

// Simulated database connection
$connection = mysql_connect('localhost', 'username', 'password');
mysql_select_db('dbname', $connection);

$id = $_GET['id'];
$id = filter($id);
echo $id; // <================================================= here
$query = "SELECT * FROM users WHERE `id` = '$id' AND 1=0;"; // Example query
$result = mysql_query($query, $connection);
// ...
?>
``` 
if my ``` $id = "  ' or 1=1 ;--  "; ```
after passing the filter ``` $id = "  \' or 1=1 ;--  "; ```

if my ``` $id = "  \x27 or 1=1 ;--  "; ```
after passing the filter ``` $id = "  \\x27 or 1=1 ;--  "; ```
