### ISSUE TITLE
SIMPLE payload without Prefix and Suffix

### ISSUE THREAD

**Issue by nonrect** [sqlmapproject/sqlmap#5591]
Hey

I recently posted an issue for this subject:
      • [sqlmap/issues/5579](https://github.com/sqlmapproject/sqlmap/issues/5579)

I tried everything with SQLMap to inject the proper time-based payload without any prefix or suffix and without any URL-Encoding, but apparently not possible

I used another tool called "**Ghauri**" which is way weaker than **SQLMap** and has a lot of bugs (not to mention the lack of many options), BUT it injected this specific time-based payload correctly

- assuming this is my vulnerable URL (* for injection point):
      • `https://target.com/bus/show/*/21648-131`
- with "Ghauri" I tried the following string and it successfully injected the proper payload
      • `ghauri -u "https://target.com/bus/show/*/21648-131" --batch --level=3 --technique="T"`
- result:
```
         ---
         Parameter: #1* (URI)
             Type: time-based blind
             Title: MySQL >= 5.0.12 time-based blind (query SLEEP)
             Payload: https://target.com/bus/show/(SELECT(0)FROM(SELECT(SLEEP(9)))a)/21648-131
         ---
```

and yes i extracted some information like --current-user, --current-db  successfully

unfortunately I couldn't achieve this with SQLMap even after trying so many different options

am I missing something or it's an issue it's just not possible at the moment ?

thanks

**Comment by stamparm** [comment]
dear user. as in majority of similar issues, i would suggest you to actually try something out of those payloads in (e.g.) browser and try to extract at least one usable bit of information. text that you provided unfortunately doesn't have any usable information apart that a tool called "Ghauri" (particularly dumb rewritten version of sqlmap, where author thought that rewriting XML to python will just give him rights to say "i made it") is able to do it.

if you are not able to provide any usable information in future, i'll assume that you are just trolling, because in that previous issue you've made i stated clearly problems in your "case"

**Comment by nonrect** [comment]
no why should I troll

as I said I did extract data successfully including --current-user and --current-db

as for information about the target, the only reason I didn't post the actual target is because I thought there are rules to not show the actual target

as for this tool I fully understand it's not that important but the only difference is the type of payload it sends which leads to exploiting the target while I tried numerous things with sqlmap to achieve the same thing but couldn't

do you want me to send you the actual target for test?

**Comment by stamparm** [comment]
oh man, this is getting seriously concerning. let me repeat from last two issues:

1) `i would suggest you to actually try something out of those payloads in (e.g.) browser and try to extract at least one usable bit of information`
2) `always use valid parameters. putting -6 just for fun won't help`
3) `do a proper debugging. run with -v 3 and -t traffic.txt to inspect what's going on`
