### ISSUE TITLE
Error checking for time based blind

### ISSUE THREAD

**Issue by arnimr** [sqlmapproject/sqlmap#568]
Hello,

first: thanks for that great tool, awesome!

I'm experiencing some wrong characters received (printable) from a really slow web/db-server with time based blind, e.g. the table name would be "admin_uLers". That could probably be fixed quite easy and without costing additional time, if everything is ok. The idea would be:
- after receiving the whole string, send one more query like "is this string correct?"
- if yes, fine, we didn't have to wait X seconds
- if not, feed the wrong string in output prediction and try again

luxury would be to have the output prediction continue after the 1st wrong character.

bye
arnim

**Comment by berney** [comment]
I'm finding frequent errors, and it seems there's no easy way except --fresh-queries to get the correct names, and then I think the incorrect names would still be in the session.sqlite saved data.

I think checking the whole name, even though each byte is checked as it's determined is a good idea, it's one extra query per table. If the whole name check comes back as failed perhaps the name can be split in half and each half checked, etc. to do a binary search for the error, if both halves come back with no errors then it could be deemed the failed whole name check was a false negative due to server/network lags. Each additional check that comes back verifying the old checks makes in more statistically probable that the answer is correct.

I think it's important to get the correct names, as later enumerations, such as schemas, column names, row counts, etc. depend on the table name being correct.

If people don't desire the extra reliability, perhaps this feature could be have an option to enable (or disable) it.

Alternatively perhaps some hamming code can be used or something to get more reliability.

**Comment by stamparm** [comment]
@berney just one stupid question. As you probably don't know there is already a validity check per character. It obviously fails in certain situations (network lags). How in your perfect scenario would you distinguish if a validity check for a word is actually a TRUE response or just a network lag. You are actually potentially sacrificing a perfectly valid word in case of a FALSE response for a validity check. I am closing this down because you don't understand the matter enough

**Comment by berney** [comment]
I know there is already a validity check per byte. I don't think you read my comment properly, as I said "I think checking the whole name, *even though each byte is checked as it's determined* is a good idea".

I also read you earlier comment about further checks also being vulnerable to the same lag and proposed and algorithm. For distinguishing if a validity check for a word is actually true versus network lag, I proposed that the if the whole word check fails the word is split in half, and each half checked (so 2 more queries if the whole word check fails), if these 2 pass then presume the whole word check failing was a false negative - i.e. the word is actually correct).

By doing redundant checks, each redundant check is adding more certainty that the value is correct and not corrupted due to network or server lag.

**Comment by stamparm** [comment]
Then why don't you just use a high value for --time-sec? That's also a form of redundancy. Also, checking half and half of word is a perfect nonsense as in case of a VALIDITY MISS you are invalidating a perfect word

**Comment by berney** [comment]
My understanding is that --time-sec sets the delay time, for example as in WAITFOR DELAY '0:0:x', making it higher means network/server lag is less likely to cause invalid inferences (lag needs to spike above the time-sec delay). If my understanding is correct, --time-sec, does *not* provide any redundancy. The byte-check in getChar that calls validateByte and then increments timeSec provides redundancy.

The OP suggested a 2nd redundancy check, which I'm backing. Regarding the validity miss problem, my proposal is that each time a validity check fails, you halve the length you are checking, until it's down to a byte, and then you getChar that byte again (in the case that checks keep failing). If the failures are due to lag, the subsequent checks are more likely to pass, in which case it's presumed the failed check was a false negative and the value is actually correct, so the perfect word is not invalidated.

In the current implementation, if a 1 inferred bit of the current char is wrong due to lag, the inferred character is wrong, if the byte check is wrong due to lag, then this incorrect value is used. If there are 8 checks one for each bit, plus 1 additional to check the byte, there's 9 checks per byte. If there's 2 bit-flips in 9 queries due to lag the incorrect value will be inferred. 

The OP proposed 1 additional check for the table name, which I'm backing. For a 10-byte table name currently there would be 90 queries, OP proposes 91, I propose 91, if that 91th query comes back bad, then do 2 more, if they come back good then keep the table name as discovered, for each that comes back bad do 2 more until either both halves checked come back good, or a byte appears bad, getChar that byte again.

So if all bytes are inferred correctly and the word check is a validity miss, 2 more queries are done, and they are hits, you have 93 queries to get the same end result, and over head of 3 queries.

If one byte is incorrect, and the whole table name check finds it, further queries narrow it down to bytes 5..9, then to bytes 5..7, then to bytes 5..6, then to byte 6, getChar on byte 6. Check whole table name again. This added redundancy recovers from spurious errors due to lag spikes. The redundant checks improve the certainty that the inference is correct.

**Comment by lukapusic** [comment]
@berney "if that 91th query comes back bad, then do 2 more" <- it can very easily come back good for a bad result. Or come back bad for a good result - or come back bad somewhere in the middle of validity bisection, which messes it up.

Perhaps implementing a switch for multiple final checks could work...

--recheck password_hash --recheck-times 5

Then calculate the average result of validity checks. Retrieve column again if n_valid < recheck-times/2. Take into account old values if retrieving again, to save requests.

Right now in some situations one has to open up the sql shell, retrieve the password hash several times and compare it manually to get the correct one. And then double check it with a comparison query. In cases when someone is planning to invest lots of time in cracking the hash, it's really important to have the correct one.

**Comment by berney** [comment]
Yes, it can come back good for a bad result, which would mean 3 errors out of 10+ queries, rather than only 2 errors out of 9 queries. I'd rather it need to fail 3 times to use bad data then fail to only twice to use bad data. Getting 3 spikes above the time-sec delay should be less probably than getting only 2.

Coming back bad in the middle of a validity bisection should just cause it to bisect further, each false negative would cause 2 more queries, if they come back true positive the bisection stops with the algorithm presuming there was a false negative. The algorithm may still infer incorrect data if false negatives keep occurring, but if they are spurious, then the algorithm should recover.

Your idea of checking the results multiple times and voting on it is also a good idea IMO.

My proposed algorithm is similar in a way, where it is taking into account old results to save queries and voting based on the bisection e.g. if 10 byte check comes back with a false negative but 2x 5 bytes comes back as positive then the votes is 1 (original inferences) - 1 (false negative on 10 bytes) + 1 (2x5) -> original inference is deemed good.

I think that each redundant check adds more probability that the value infered is correct, so multiple checks is warranted, especially in the case you point out like cracking password hashes.

**Comment by stamparm** [comment]
@berney not any kind of rechecking of (e.g. half) splitted result will ever be done
@lukapusic some kind of user assisted (e.g. via option) rechecks will be done

**Comment by stamparm** [comment]
Duplicate of #1973
