### ISSUE TITLE
Updating sqlmap error !!!

### ISSUE THREAD

**Issue by Paladin88** [sqlmapproject/sqlmap#635]
How to fix this error ?

[ERROR] not a git repository. Please checkout the 'sqlmapproject/sqlmap' repository from GitHub (e.g. git clone https://github.com/sqlmapproject/sqlmap.git sqlmap-dev)

**Comment by ashee69** [comment]
hello stamparm,
i have also been stuck with this stupid problem.
please have a look at it though i know it is not that important but i want to figure out where the problem is
i gonna paste here commands and result one by one
# sqlmap --version
sqlmap/1.0-dev
             it does not tell the revision thats why i wasnt aware of thing.
             anyhow i tried to update
#sqlmap --update
[05:30:22] [ERROR] not a git repository. Please checkout the 'sqlmapproject/sqlmap' repository from GitHub (e.g. git clone https://github.com/sqlmapproject/sqlmap.git sqlmap-dev)
[05:30:22] [INFO] for Linux platform it's required to install a standard 'git' package (e.g.: 'sudo apt-get install git')

              i kept on going

# sudo apt-get install git
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version.
           i did this too
# git clone https://github.com/sqlmapproject/sqlmap.git sqlmap-dev
           but it installed a new sqlmap in the current directory

the thing is my sqlmap (i.e.the command sqlmap) which is situated at /usr/share/sqlmap is still obsolete beside i daily issue commands like apt-get update and apt-get upgrade.
it has these only folders
http://gyazo.com/777ff386d9b2127e3e320279708437fb
then i learnt that a few folders are missing there like waf and some git related files
i tried your patch too.  Patch for an Issue #1010       
                 
right now i am using sqlmap installed with tarball but whats wrong with my pc.
please help.

**Comment by stamparm** [comment]
@ashee69 you should:

1) completely remove the old version of sqlmap (e.g. `sudo apt-get remove sqlmap` if you installed it from repository or just `rm -rf /usr/share/sqlmap`)
2) go to the parent directory where you want sqlmap to be installed (e.g. `cd /usr/share`)
3) clone the git repository (e.g. `git clone https://github.com/sqlmapproject/sqlmap.git sqlmap`)

now, /usr/share/sqlmap should hold the latest sqlmap revision from our git repository

**Comment by kofa2002** [comment]
because you have sqlmap installed with pip you have to do 

pip install --upgrade sqlmap
