### ISSUE TITLE
Dump specific entry

### ISSUE THREAD

**Issue by caizixian** [sqlmapproject/sqlmap#750]
Like can I dump a entry with it's id=1 or a entry whose name='username' Ps I got the table name colmun name database name.

**Comment by tibou1205** [comment]
hello 
sqlmap.py -u http://..... --dump -T ....-D ..... --where "id>12" and "cp>90"
is the next synutax correct?

**Comment by stamparm** [comment]
@tibou1205 `--where "id>12 and cp>90"`

**Comment by sharifulgeo** [comment]
Can I use like operator inside where clause e.g. `--where "Id like '*AHWR43*'"` . I need alternative to this types of command at least to dump only partially corrupt ids.

**Comment by stamparm** [comment]
@sharifulgeo yes, you can.

example:
```
python sqlmap.py -u "http://testphp.vulnweb.com/artists.php?artist=1" --batch -D acuart -T artists --dump --where "aname LIKE 'r4%'"
```

**Comment by sharifulgeo** [comment]
I need to do a IN check, to avoid already dumped IDs, using where clause like `--where "RowId NOT IN (SELECT RowId FROM TL_GenerateTradeLicense)"` can I do this? For me where clause like above does not work. I am going this way since my `(SELECT RowId FROM TL_GenerateTradeLicense)` returns almost 200000 entries. Is there any other way to go with?
